// AUTO-GENERATED by tools/placement_studio — do not hand-edit.
// Per-animation render scale applied as the PIG-CARD transform so every
// pose reads at ~the same size as idle (sprite + items scale together).
// Tune in the Placement Studio (Items mode -> Pose -> Scale).
export const ANIM_SCALE: Record<string, number> = {
	idle: 1,
	walk: 1,
	jump: 1,
	happy: 1,
	sad: 1.04,
	tired: 1.11,
	surprise: 1.24,
	wave: 1.37,
};
