// AUTO-GENERATED by tools/placement_studio — do not hand-edit.
// Per-animation render scale applied as the PIG-CARD transform so every
// pose reads at ~the same size as idle (sprite + items scale together).
// Tune in the Placement Studio (Items mode -> Pose -> Scale).
export const ANIM_SCALE: Record<string, number> = {
	idle: 0.6,
	walk: 1,
	jump: 1.015,
	happy: 0.979,
	sad: 1.045,
	tired: 1.106,
	surprise: 0.975,
	wave: 1.044,
};
