import type { HabitatCatalogItem } from "@/utils/habitat";

export type HabitatExpansionCollection = {
  id: string;
  name: string;
  paidItemIds: readonly string[];
  rewards: readonly { itemId: string; threshold: 4 | 8 }[];
};

export const HABITAT_EXPANSION_CATALOG = [
  {
    id: "apple_crate_stool",
    name: "Apple Crate Stool",
    description:
      "An apple-stamped crate with a plump sage cushion offers the perfect cider-break perch.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "apple_crate_stool",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1000,
    collectionId: "orchard_morning",
  },
  {
    id: "pearwood_rocker",
    name: "Pearwood Rocker",
    description:
      "Curved pearwood rockers and a leaf-stitched seat make slow mornings even sweeter.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "pearwood_rocker",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1010,
    collectionId: "orchard_morning",
  },
  {
    id: "cider_jug_lamp",
    name: "Cider Jug Lamp",
    description: "A little amber jug keeps the evening light warm.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "cider_jug_lamp",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1020,
    collectionId: "orchard_morning",
  },
  {
    id: "orchard_boot_rack",
    name: "Orchard Boot Rack",
    description: "Muddy boots line up beneath four apple-shaped pegs.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "orchard_boot_rack",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1030,
    collectionId: "orchard_morning",
  },
  {
    id: "blossom_branch_print",
    name: "Blossom Branch Print",
    description:
      "A flowering branch and two bluebirds preserve the first bright day of spring.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "blossom_branch_print",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1040,
    collectionId: "orchard_morning",
  },
  {
    id: "apple_picking_apron",
    name: "Apple-Picking Apron",
    description:
      "Rosy pockets and a stitched apple make this apron look freshly home from picking.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "apple_picking_apron",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1050,
    collectionId: "orchard_morning",
  },
  {
    id: "bluebird_sugar_bowl",
    name: "Bluebird Sugar Bowl",
    description:
      "A round bluebird lid guards the sugar cubes from curious snouts.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "bluebird_sugar_bowl",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1060,
    collectionId: "orchard_morning",
  },
  {
    id: "tiny_cider_press",
    name: "Tiny Cider Press",
    description:
      "One tiny crank turns a basket of apples into make-believe cider.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "tiny_cider_press",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1070,
    collectionId: "orchard_morning",
  },
  {
    id: "blossom_bough_mobile",
    name: "Blossom Bough Mobile",
    description:
      "Paper blossoms and carved leaves drift softly above the room.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "blossom_bough_mobile",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1080,
    collectionId: "orchard_morning",
    rewardThreshold: 4,
  },
  {
    id: "orchard_round_rug",
    name: "Orchard Round Rug",
    description:
      "Rings of apples, leaves, and cream braid the orchard into one welcoming circle.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "orchard_round_rug",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1090,
    collectionId: "orchard_morning",
    rewardThreshold: 8,
  },
  {
    id: "ladderback_supper_chair",
    name: "Ladderback Supper Chair",
    description:
      "A red-spindled chair waits patiently for whoever reaches supper first.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "ladderback_supper_chair",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1100,
    collectionId: "hearthside_supper",
  },
  {
    id: "beanpot_footstool",
    name: "Beanpot Footstool",
    description:
      "The beanpot’s checked cushion turns kitchen clutter into a cozy footrest.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "beanpot_footstool",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1110,
    collectionId: "hearthside_supper",
  },
  {
    id: "copper_kettle_lamp",
    name: "Copper Kettle Lamp",
    description: "A hammered copper kettle pours golden light instead of tea.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "copper_kettle_lamp",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1120,
    collectionId: "hearthside_supper",
  },
  {
    id: "rolling_pie_cart",
    name: "Rolling Pie Cart",
    description:
      "A flour-dusted cart carries a cooling berry pie on bright red wheels.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "rolling_pie_cart",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1130,
    collectionId: "hearthside_supper",
  },
  {
    id: "family_recipe_board",
    name: "Family Recipe Board",
    description:
      "Rosie’s favorite pie recipe curls across a chalk-dark kitchen board.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "family_recipe_board",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1140,
    collectionId: "hearthside_supper",
  },
  {
    id: "gingham_oven_mitts",
    name: "Gingham Oven Mitts",
    description:
      "Two gingham mitts hang together as if supper has just left the oven.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "gingham_oven_mitts",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1150,
    collectionId: "hearthside_supper",
  },
  {
    id: "butter_bell",
    name: "Butter Bell",
    description: "A sunny yellow butter bell wears a tiny red checked cap.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "butter_bell",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1160,
    collectionId: "hearthside_supper",
  },
  {
    id: "pie_bird_crock",
    name: "Pie Bird Crock",
    description:
      "A black ceramic pie bird peeks from a crock of wooden baking spoons.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "pie_bird_crock",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1170,
    collectionId: "hearthside_supper",
  },
  {
    id: "copper_pan_chime",
    name: "Copper Pan Chime",
    description:
      "Little copper pans chime whenever a happy draft crosses the rafters.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "copper_pan_chime",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1180,
    collectionId: "hearthside_supper",
    rewardThreshold: 4,
  },
  {
    id: "braided_hearth_mat",
    name: "Braided Hearth Mat",
    description:
      "Thick tomato and cream braids make the hearth feel warm before the fire is lit.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "braided_hearth_mat",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1190,
    collectionId: "hearthside_supper",
    rewardThreshold: 8,
  },
  {
    id: "wicker_picnic_chair",
    name: "Wicker Picnic Chair",
    description:
      "A wicker chair with a strawberry cushion feels like lunch beneath an open sky.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "wicker_picnic_chair",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1200,
    collectionId: "meadow_picnic",
  },
  {
    id: "daisy_cushion_pouf",
    name: "Daisy Cushion Pouf",
    description:
      "A giant daisy pouf makes sitting on the floor feel like finding a flower.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "daisy_cushion_pouf",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1210,
    collectionId: "meadow_picnic",
  },
  {
    id: "lemonade_stand",
    name: "Lemonade Stand",
    description:
      "A striped awning and glass lemonade jar bring the county fair indoors.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "lemonade_stand",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1220,
    collectionId: "meadow_picnic",
  },
  {
    id: "folded_quilt_bench",
    name: "Folded Quilt Bench",
    description:
      "A folded patchwork quilt softens a simple green picnic bench.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "folded_quilt_bench",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1230,
    collectionId: "meadow_picnic",
  },
  {
    id: "pressed_daisy_chart",
    name: "Pressed Daisy Chart",
    description:
      "Pressed daisies are labeled in careful pencil like treasures from the meadow.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "pressed_daisy_chart",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1240,
    collectionId: "meadow_picnic",
  },
  {
    id: "kite_tail_banner",
    name: "Kite-Tail Banner",
    description:
      "A kite tail of knotted ribbons skips across the wall without any wind.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "kite_tail_banner",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1250,
    collectionId: "meadow_picnic",
  },
  {
    id: "strawberry_jam_jar",
    name: "Strawberry Jam Jar",
    description:
      "Ruby jam catches the light beneath a strawberry-shaped cloth lid.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "strawberry_jam_jar",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1260,
    collectionId: "meadow_picnic",
  },
  {
    id: "ladybug_tea_tin",
    name: "Ladybug Tea Tin",
    description:
      "A red ladybug tin hides tea bags beneath two glossy black wings.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "ladybug_tea_tin",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1270,
    collectionId: "meadow_picnic",
  },
  {
    id: "ribbon_kite_mobile",
    name: "Ribbon Kite Mobile",
    description: "A tiny kite and eight ribbon bows circle lazily overhead.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "ribbon_kite_mobile",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1280,
    collectionId: "meadow_picnic",
    rewardThreshold: 4,
  },
  {
    id: "picnic_check_rug",
    name: "Picnic Check Rug",
    description:
      "Red checks, blue corners, and a daisy border spread a picnic across the floor.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "picnic_check_rug",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1290,
    collectionId: "meadow_picnic",
    rewardThreshold: 8,
  },
  {
    id: "yellow_welly_stand",
    name: "Yellow Welly Stand",
    description: "Four yellow wellies drip neatly into a cloud-blue tray.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "yellow_welly_stand",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1300,
    collectionId: "rainy_barn_day",
  },
  {
    id: "puddle_blue_settee",
    name: "Puddle-Blue Settee",
    description:
      "A deep blue settee curves like a friendly puddle without getting anyone wet.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "puddle_blue_settee",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1310,
    collectionId: "rainy_barn_day",
  },
  {
    id: "umbrella_floor_lamp",
    name: "Umbrella Floor Lamp",
    description: "A yellow umbrella shade makes every rainy corner feel sunny.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "umbrella_floor_lamp",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1320,
    collectionId: "rainy_barn_day",
  },
  {
    id: "raincoat_pegs",
    name: "Raincoat Pegs",
    description:
      "Raincoats and hats wait on a sturdy tree that stands clear of the wall.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "raincoat_pegs",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1330,
    collectionId: "rainy_barn_day",
  },
  {
    id: "cloudspotters_chart",
    name: "Cloudspotter’s Chart",
    description:
      "Cloud shapes and tiny silver arrows turn weather watching into an art.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "cloudspotters_chart",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1340,
    collectionId: "rainy_barn_day",
  },
  {
    id: "rainy_window_sampler",
    name: "Rainy Window Sampler",
    description:
      "Stitched raindrops bead across a window that is always cozy on this side.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "rainy_window_sampler",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1350,
    collectionId: "rainy_barn_day",
  },
  {
    id: "frog_weather_vane",
    name: "Frog Weather Vane",
    description:
      "A green frog points toward fair weather from his tiny rooftop arrow.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "frog_weather_vane",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1360,
    collectionId: "rainy_barn_day",
  },
  {
    id: "snail_mail_box",
    name: "Snail-Mail Box",
    description:
      "A smiling snail carries rolled notes inside its blue shell mailbox.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "snail_mail_box",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1370,
    collectionId: "rainy_barn_day",
  },
  {
    id: "raindrop_bell_mobile",
    name: "Raindrop Bell Mobile",
    description:
      "Glass raindrops ring three pewter bells with a soft shower-song.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "raindrop_bell_mobile",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1380,
    collectionId: "rainy_barn_day",
    rewardThreshold: 4,
  },
  {
    id: "puddle_ring_rug",
    name: "Puddle-Ring Rug",
    description:
      "Concentric blue rings and one embroidered frog make a puddle safe for hooves.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "puddle_ring_rug",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1390,
    collectionId: "rainy_barn_day",
    rewardThreshold: 8,
  },
  {
    id: "pumpkin_cushion_chair",
    name: "Pumpkin Cushion Chair",
    description:
      "A ribbed pumpkin chair gives every sitter the best seat at the harvest dance.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "pumpkin_cushion_chair",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1400,
    collectionId: "harvest_hoedown",
  },
  {
    id: "cornshuck_ottoman",
    name: "Cornshuck Ottoman",
    description:
      "Bound corn husks wrap a golden cushion made for tapping hooves.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "cornshuck_ottoman",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1410,
    collectionId: "harvest_hoedown",
  },
  {
    id: "pitchfork_coat_tree",
    name: "Pitchfork Coat Tree",
    description: "A polished pitchfork grows hooks for hats instead of hay.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "pitchfork_coat_tree",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1420,
    collectionId: "harvest_hoedown",
  },
  {
    id: "barrel_side_table",
    name: "Barrel Side Table",
    description: "A half barrel holds cider cups beside the dance floor.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "barrel_side_table",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1430,
    collectionId: "harvest_hoedown",
  },
  {
    id: "harvest_moon_print",
    name: "Harvest Moon Print",
    description:
      "A huge cream moon rises behind a tiny red barn and rows of corn.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "harvest_moon_print",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1440,
    collectionId: "harvest_hoedown",
  },
  {
    id: "calico_dance_banner",
    name: "Calico Dance Banner",
    description:
      "Calico squares and dancing hoofprints march across a festive banner.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "calico_dance_banner",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1450,
    collectionId: "harvest_hoedown",
  },
  {
    id: "acorn_candleholder",
    name: "Acorn Candleholder",
    description: "A brass acorn cup cradles one beeswax flame.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "acorn_candleholder",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1460,
    collectionId: "harvest_hoedown",
  },
  {
    id: "mini_fiddle_case",
    name: "Mini Fiddle Case",
    description:
      "A walnut fiddle sleeps in a plum-lined case barely bigger than an apple.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "mini_fiddle_case",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1470,
    collectionId: "harvest_hoedown",
  },
  {
    id: "corn_tassel_chandelier",
    name: "Corn-Tassel Chandelier",
    description:
      "Corn tassels and wooden beads tumble from a wagon-wheel ring.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "corn_tassel_chandelier",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1480,
    collectionId: "harvest_hoedown",
    rewardThreshold: 4,
  },
  {
    id: "hoedown_star_rug",
    name: "Hoedown Star Rug",
    description:
      "An eight-point harvest star spins through pumpkin, plum, and corn-gold wool.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "hoedown_star_rug",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1490,
    collectionId: "harvest_hoedown",
    rewardThreshold: 8,
  },
  {
    id: "spool_leg_stool",
    name: "Spool-Leg Stool",
    description:
      "A giant thread spool becomes a clever stool for small inventors.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "spool_leg_stool",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1500,
    collectionId: "tinkers_workshop",
  },
  {
    id: "patched_tool_chest",
    name: "Patched Tool Chest",
    description:
      "Every dent in this blue tool chest looks earned and carefully mended.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "patched_tool_chest",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1510,
    collectionId: "tinkers_workshop",
  },
  {
    id: "oilcan_task_lamp",
    name: "Oilcan Task Lamp",
    description:
      "A brass oilcan bends its long spout over a focused pool of light.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "oilcan_task_lamp",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1520,
    collectionId: "tinkers_workshop",
  },
  {
    id: "folding_sawhorse_table",
    name: "Folding Sawhorse Table",
    description:
      "Two folding sawhorses hold a pine top scattered with one perfect pencil.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "folding_sawhorse_table",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1530,
    collectionId: "tinkers_workshop",
  },
  {
    id: "blueprint_pinboard",
    name: "Blueprint Pinboard",
    description:
      "Pinned plans reveal a marvelous machine powered mostly by optimism.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "blueprint_pinboard",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1540,
    collectionId: "tinkers_workshop",
  },
  {
    id: "wooden_gear_clock",
    name: "Wooden Gear Clock",
    description: "Exposed wooden gears tick around a tiny brass bell.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "wooden_gear_clock",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1550,
    collectionId: "tinkers_workshop",
  },
  {
    id: "button_sorter_tray",
    name: "Button Sorter Tray",
    description:
      "Rows of bright buttons sort themselves into a satisfying rainbow.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "button_sorter_tray",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1560,
    collectionId: "tinkers_workshop",
  },
  {
    id: "windup_pig_toy",
    name: "Wind-Up Pig Toy",
    description:
      "A tin pig marches forward whenever its brass key gets a turn.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "windup_pig_toy",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1570,
    collectionId: "tinkers_workshop",
  },
  {
    id: "pulley_cage_light",
    name: "Pulley-Cage Light",
    description:
      "A caged workshop bulb rises and falls on a real little pulley.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "pulley_cage_light",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1580,
    collectionId: "tinkers_workshop",
    rewardThreshold: 4,
  },
  {
    id: "measuring_tape_rug",
    name: "Measuring-Tape Rug",
    description:
      "A curling yellow tape measure marks out a playful path across blue canvas.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "measuring_tape_rug",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1590,
    collectionId: "tinkers_workshop",
    rewardThreshold: 8,
  },
  {
    id: "toadstool_reading_seat",
    name: "Toadstool Reading Seat",
    description:
      "A red-capped toadstool makes chapter time feel like a woodland secret.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "toadstool_reading_seat",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1600,
    collectionId: "storybook_nook",
  },
  {
    id: "stacked_book_step",
    name: "Stacked-Book Step",
    description:
      "Three oversized books stack into a sturdy step for reaching the next tale.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "stacked_book_step",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1610,
    collectionId: "storybook_nook",
  },
  {
    id: "pencil_post_lamp",
    name: "Pencil-Post Lamp",
    description:
      "A sharpened yellow pencil holds a pleated paper shade above late-night readers.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "pencil_post_lamp",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1620,
    collectionId: "storybook_nook",
  },
  {
    id: "little_library_cart",
    name: "Little Library Cart",
    description:
      "A wheeled teal library cart keeps favorite tales within easy trotting distance.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "little_library_cart",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1630,
    collectionId: "storybook_nook",
  },
  {
    id: "once_upon_a_barn_map",
    name: "Once-Upon-a-Barn Map",
    description:
      "A curling map leads from the Barn to castles, woods, and one suspiciously round dragon.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "once_upon_a_barn_map",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1640,
    collectionId: "storybook_nook",
  },
  {
    id: "paper_crown_shadowbox",
    name: "Paper Crown Shadowbox",
    description:
      "A crinkled gold paper crown looks surprisingly grand inside its deep blue box.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "paper_crown_shadowbox",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1650,
    collectionId: "storybook_nook",
  },
  {
    id: "inkpot_and_quill",
    name: "Inkpot and Quill",
    description:
      "A teal inkpot and striped feather wait beside one unfinished sentence.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "inkpot_and_quill",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1660,
    collectionId: "storybook_nook",
  },
  {
    id: "three_bears_bookends",
    name: "Three Bears Bookends",
    description: "Three carved bears hold up a row of bedtime books.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "three_bears_bookends",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1670,
    collectionId: "storybook_nook",
  },
  {
    id: "paper_star_canopy",
    name: "Paper-Star Canopy",
    description: "Folded paper stars float beneath an indigo cloth canopy.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "paper_star_canopy",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1680,
    collectionId: "storybook_nook",
    rewardThreshold: 4,
  },
  {
    id: "alphabet_story_rug",
    name: "Alphabet Story Rug",
    description:
      "Bright stitched letters wander around a book-shaped center panel.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "alphabet_story_rug",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1690,
    collectionId: "storybook_nook",
    rewardThreshold: 8,
  },
  {
    id: "sheepskin_slipper_chair",
    name: "Sheepskin Slipper Chair",
    description:
      "A cream slipper chair wraps its sitter like the warmest mitten.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "sheepskin_slipper_chair",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1700,
    collectionId: "winter_woolens",
  },
  {
    id: "mitten_storage_bench",
    name: "Mitten Storage Bench",
    description:
      "A long red bench hides scarves beneath a lid tufted like a mitten cuff.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "mitten_storage_bench",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1710,
    collectionId: "winter_woolens",
  },
  {
    id: "candycane_floor_lamp",
    name: "Candy-Cane Floor Lamp",
    description:
      "Red and cream stripes climb to a lamp glowing like holiday candy.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "candycane_floor_lamp",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1720,
    collectionId: "winter_woolens",
  },
  {
    id: "sled_blanket_rack",
    name: "Sled Blanket Rack",
    description:
      "An old green sled leans upright with three folded blankets on its rails.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "sled_blanket_rack",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1730,
    collectionId: "winter_woolens",
  },
  {
    id: "snowy_barn_papercut",
    name: "Snowy Barn Papercut",
    description:
      "Cut-paper snow settles around a tiny cranberry barn without ever melting.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "snowy_barn_papercut",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1740,
    collectionId: "winter_woolens",
  },
  {
    id: "wool_swatch_sampler",
    name: "Wool-Swatch Sampler",
    description:
      "Twelve little wool squares turn mending scraps into a proud wall sampler.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "wool_swatch_sampler",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1750,
    collectionId: "winter_woolens",
  },
  {
    id: "cocoa_marshmallow_mug",
    name: "Cocoa Marshmallow Mug",
    description:
      "Marshmallows crowd a blue mug painted with one sleepy snowpig.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "cocoa_marshmallow_mug",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1760,
    collectionId: "winter_woolens",
  },
  {
    id: "tiny_knitting_basket",
    name: "Tiny Knitting Basket",
    description: "Two tiny birch needles rest in a basket of cranberry yarn.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "tiny_knitting_basket",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1770,
    collectionId: "winter_woolens",
  },
  {
    id: "snowflake_wool_mobile",
    name: "Snowflake Wool Mobile",
    description: "Cream wool snowflakes turn slowly beneath an evergreen hoop.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "snowflake_wool_mobile",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1780,
    collectionId: "winter_woolens",
    rewardThreshold: 4,
  },
  {
    id: "cozy_cableknit_rug",
    name: "Cozy Cable-Knit Rug",
    description:
      "Oversized cream cable stitches make the floor look wrapped in a sweater.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "cozy_cableknit_rug",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1790,
    collectionId: "winter_woolens",
    rewardThreshold: 8,
  },
  {
    id: "lily_pad_floor_cushion",
    name: "Lily-Pad Floor Cushion",
    description:
      "A broad green lily pad and pink bud make a delightfully splash-free seat.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "lily_pad_floor_cushion",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1800,
    collectionId: "pondside_summer",
  },
  {
    id: "reed_woven_chair",
    name: "Reed-Woven Chair",
    description:
      "Bent pond reeds weave into a breezy chair with a striped coral cushion.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "reed_woven_chair",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1810,
    collectionId: "pondside_summer",
  },
  {
    id: "firefly_bottle_lamp",
    name: "Firefly Bottle Lamp",
    description:
      "Golden fireflies blink inside a blue bottle beneath a leaf-green shade.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "firefly_bottle_lamp",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1820,
    collectionId: "pondside_summer",
  },
  {
    id: "fishing_creel_table",
    name: "Fishing Creel Table",
    description:
      "A lidded fishing creel makes a sturdy table for lemonade and pebble collections.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "fishing_creel_table",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1830,
    collectionId: "pondside_summer",
  },
  {
    id: "dragonfly_field_print",
    name: "Dragonfly Field Print",
    description:
      "Jewel-bright dragonflies hover over careful pond notes and reed sketches.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "dragonfly_field_print",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1840,
    collectionId: "pondside_summer",
  },
  {
    id: "striped_swim_towel",
    name: "Striped Swim Towel",
    description:
      "A coral-and-blue swim towel hangs in sun-faded stripes and jaunty fringe.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "striped_swim_towel",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1850,
    collectionId: "pondside_summer",
  },
  {
    id: "duckling_watering_can",
    name: "Duckling Watering Can",
    description:
      "A yellow duckling watering can tips its beak toward a pot of pond grass.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "duckling_watering_can",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1860,
    collectionId: "pondside_summer",
  },
  {
    id: "pebble_fountain_bowl",
    name: "Pebble Fountain Bowl",
    description:
      "Smooth blue pebbles circle a tiny fountain no taller than a teacup.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "pebble_fountain_bowl",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1870,
    collectionId: "pondside_summer",
  },
  {
    id: "cattail_lantern_string",
    name: "Cattail Lantern String",
    description:
      "Cattail shades hide a string of firefly-gold bulbs above the room.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "cattail_lantern_string",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1880,
    collectionId: "pondside_summer",
    rewardThreshold: 4,
  },
  {
    id: "pond_ripple_rug",
    name: "Pond-Ripple Rug",
    description:
      "Blue ripples circle three lily leaves and one coral dragonfly.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "pond_ripple_rug",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1890,
    collectionId: "pondside_summer",
    rewardThreshold: 8,
  },
  {
    id: "crescent_nap_chair",
    name: "Crescent Nap Chair",
    description:
      "A crescent-shaped chair cradles naps beneath a single golden star pillow.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "crescent_nap_chair",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1900,
    collectionId: "moonlit_slumber",
  },
  {
    id: "cloud_pillow_hamper",
    name: "Cloud-Pillow Hamper",
    description:
      "A lavender hamper overflows with pillows shaped like drowsy little clouds.",
    category: "floor_decor",
    rarity: "common",
    assetKey: "cloud_pillow_hamper",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1910,
    collectionId: "moonlit_slumber",
  },
  {
    id: "starlight_floor_lantern",
    name: "Starlight Floor Lantern",
    description:
      "A pierced indigo lantern scatters tiny stars across the floor.",
    category: "floor_decor",
    rarity: "uncommon",
    assetKey: "starlight_floor_lantern",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1920,
    collectionId: "moonlit_slumber",
  },
  {
    id: "bedtime_trunk",
    name: "Bedtime Trunk",
    description:
      "A midnight-blue trunk keeps quilts, books, and tomorrow’s dreams safely tucked away.",
    category: "floor_decor",
    rarity: "rare",
    assetKey: "bedtime_trunk",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1930,
    collectionId: "moonlit_slumber",
  },
  {
    id: "constellation_stitchery",
    name: "Constellation Stitchery",
    description:
      "Golden thread joins the stars into a pig-shaped constellation.",
    category: "wall_decor",
    rarity: "common",
    assetKey: "constellation_stitchery",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1940,
    collectionId: "moonlit_slumber",
  },
  {
    id: "goodnight_pig_portrait",
    name: "Goodnight Pig Portrait",
    description:
      "A tiny pig in a nightcap waves goodnight from a moon-cream frame.",
    category: "wall_decor",
    rarity: "uncommon",
    assetKey: "goodnight_pig_portrait",
    snoutCost: 100,
    isForSale: true,
    active: true,
    displayOrder: 1950,
    collectionId: "moonlit_slumber",
  },
  {
    id: "moon_milk_carafe",
    name: "Moon-Milk Carafe",
    description:
      "A frosted carafe and moon cup wait quietly for midnight thirst.",
    category: "surface_decor",
    rarity: "common",
    assetKey: "moon_milk_carafe",
    snoutCost: 50,
    isForSale: true,
    active: true,
    displayOrder: 1960,
    collectionId: "moonlit_slumber",
  },
  {
    id: "sleepy_clock",
    name: "Sleepy Clock",
    description:
      "The round blue clock looks half asleep, but its golden hands stay punctual.",
    category: "surface_decor",
    rarity: "rare",
    assetKey: "sleepy_clock",
    snoutCost: 175,
    isForSale: true,
    active: true,
    displayOrder: 1970,
    collectionId: "moonlit_slumber",
  },
  {
    id: "glowstar_dreamcatcher",
    name: "Glowstar Dreamcatcher",
    description:
      "A woven crescent catches seven glowing stars and three lavender feathers.",
    category: "ceiling_decor",
    rarity: "uncommon",
    assetKey: "glowstar_dreamcatcher",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1980,
    collectionId: "moonlit_slumber",
    rewardThreshold: 4,
  },
  {
    id: "midnight_patch_rug",
    name: "Midnight Patch Rug",
    description:
      "Indigo patches, cream moons, and lavender stars quilt bedtime across the floor.",
    category: "floor_centerpiece",
    rarity: "rare",
    assetKey: "midnight_patch_rug",
    snoutCost: 0,
    isForSale: false,
    active: true,
    displayOrder: 1990,
    collectionId: "moonlit_slumber",
    rewardThreshold: 8,
  },
] as const satisfies readonly HabitatCatalogItem[];

export const HABITAT_EXPANSION_COLLECTIONS = [
  {
    id: "orchard_morning",
    name: "Orchard Morning",
    paidItemIds: [
      "apple_crate_stool",
      "pearwood_rocker",
      "cider_jug_lamp",
      "orchard_boot_rack",
      "blossom_branch_print",
      "apple_picking_apron",
      "bluebird_sugar_bowl",
      "tiny_cider_press",
    ],
    rewards: [
      { itemId: "blossom_bough_mobile", threshold: 4 },
      { itemId: "orchard_round_rug", threshold: 8 },
    ],
  },
  {
    id: "hearthside_supper",
    name: "Hearthside Supper",
    paidItemIds: [
      "ladderback_supper_chair",
      "beanpot_footstool",
      "copper_kettle_lamp",
      "rolling_pie_cart",
      "family_recipe_board",
      "gingham_oven_mitts",
      "butter_bell",
      "pie_bird_crock",
    ],
    rewards: [
      { itemId: "copper_pan_chime", threshold: 4 },
      { itemId: "braided_hearth_mat", threshold: 8 },
    ],
  },
  {
    id: "meadow_picnic",
    name: "Meadow Picnic",
    paidItemIds: [
      "wicker_picnic_chair",
      "daisy_cushion_pouf",
      "lemonade_stand",
      "folded_quilt_bench",
      "pressed_daisy_chart",
      "kite_tail_banner",
      "strawberry_jam_jar",
      "ladybug_tea_tin",
    ],
    rewards: [
      { itemId: "ribbon_kite_mobile", threshold: 4 },
      { itemId: "picnic_check_rug", threshold: 8 },
    ],
  },
  {
    id: "rainy_barn_day",
    name: "Rainy Barn Day",
    paidItemIds: [
      "yellow_welly_stand",
      "puddle_blue_settee",
      "umbrella_floor_lamp",
      "raincoat_pegs",
      "cloudspotters_chart",
      "rainy_window_sampler",
      "frog_weather_vane",
      "snail_mail_box",
    ],
    rewards: [
      { itemId: "raindrop_bell_mobile", threshold: 4 },
      { itemId: "puddle_ring_rug", threshold: 8 },
    ],
  },
  {
    id: "harvest_hoedown",
    name: "Harvest Hoedown",
    paidItemIds: [
      "pumpkin_cushion_chair",
      "cornshuck_ottoman",
      "pitchfork_coat_tree",
      "barrel_side_table",
      "harvest_moon_print",
      "calico_dance_banner",
      "acorn_candleholder",
      "mini_fiddle_case",
    ],
    rewards: [
      { itemId: "corn_tassel_chandelier", threshold: 4 },
      { itemId: "hoedown_star_rug", threshold: 8 },
    ],
  },
  {
    id: "tinkers_workshop",
    name: "Tinker\u2019s Workshop",
    paidItemIds: [
      "spool_leg_stool",
      "patched_tool_chest",
      "oilcan_task_lamp",
      "folding_sawhorse_table",
      "blueprint_pinboard",
      "wooden_gear_clock",
      "button_sorter_tray",
      "windup_pig_toy",
    ],
    rewards: [
      { itemId: "pulley_cage_light", threshold: 4 },
      { itemId: "measuring_tape_rug", threshold: 8 },
    ],
  },
  {
    id: "storybook_nook",
    name: "Storybook Nook",
    paidItemIds: [
      "toadstool_reading_seat",
      "stacked_book_step",
      "pencil_post_lamp",
      "little_library_cart",
      "once_upon_a_barn_map",
      "paper_crown_shadowbox",
      "inkpot_and_quill",
      "three_bears_bookends",
    ],
    rewards: [
      { itemId: "paper_star_canopy", threshold: 4 },
      { itemId: "alphabet_story_rug", threshold: 8 },
    ],
  },
  {
    id: "winter_woolens",
    name: "Winter Woolens",
    paidItemIds: [
      "sheepskin_slipper_chair",
      "mitten_storage_bench",
      "candycane_floor_lamp",
      "sled_blanket_rack",
      "snowy_barn_papercut",
      "wool_swatch_sampler",
      "cocoa_marshmallow_mug",
      "tiny_knitting_basket",
    ],
    rewards: [
      { itemId: "snowflake_wool_mobile", threshold: 4 },
      { itemId: "cozy_cableknit_rug", threshold: 8 },
    ],
  },
  {
    id: "pondside_summer",
    name: "Pondside Summer",
    paidItemIds: [
      "lily_pad_floor_cushion",
      "reed_woven_chair",
      "firefly_bottle_lamp",
      "fishing_creel_table",
      "dragonfly_field_print",
      "striped_swim_towel",
      "duckling_watering_can",
      "pebble_fountain_bowl",
    ],
    rewards: [
      { itemId: "cattail_lantern_string", threshold: 4 },
      { itemId: "pond_ripple_rug", threshold: 8 },
    ],
  },
  {
    id: "moonlit_slumber",
    name: "Moonlit Slumber",
    paidItemIds: [
      "crescent_nap_chair",
      "cloud_pillow_hamper",
      "starlight_floor_lantern",
      "bedtime_trunk",
      "constellation_stitchery",
      "goodnight_pig_portrait",
      "moon_milk_carafe",
      "sleepy_clock",
    ],
    rewards: [
      { itemId: "glowstar_dreamcatcher", threshold: 4 },
      { itemId: "midnight_patch_rug", threshold: 8 },
    ],
  },
] as const satisfies readonly HabitatExpansionCollection[];

export const HABITAT_EXPANSION_CATALOG_BY_ID = Object.fromEntries(
  HABITAT_EXPANSION_CATALOG.map((item) => [item.id, item]),
) as Record<string, HabitatCatalogItem>;
