// AUTO-GENERATED by tools/gen_side_items.py — do not edit by hand.
// Rebuilt from assets/images/hats/side/ on every run: every item with a
// three-quarter sprite for the turned (`face` / `face_sit`) pig. An item
// missing here keeps its front sprite when the pig turns.

export const HAT_SIDE_IMAGES: Record<string, number> = {
	acorn_bow: require("../assets/images/hats/side/acorn_bow.png"),
	astronaut: require("../assets/images/hats/side/astronaut.png"),
	aviator_sunglasses: require("../assets/images/hats/side/aviator_sunglasses.png"),
	cocoa_sheen_specs: require("../assets/images/hats/side/cocoa_sheen_specs.png"),
	coconut_shell_shades: require("../assets/images/hats/side/coconut_shell_shades.png"),
	cowboy: require("../assets/images/hats/side/cowboy.png"),
	frost_spectacles: require("../assets/images/hats/side/frost_spectacles.png"),
	galaxy_shades: require("../assets/images/hats/side/galaxy_shades.png"),
	heart_sunglasses: require("../assets/images/hats/side/heart_sunglasses.png"),
	jam_jar_lenses: require("../assets/images/hats/side/jam_jar_lenses.png"),
	knight_visor_specs: require("../assets/images/hats/side/knight_visor_specs.png"),
	lollipop_specs: require("../assets/images/hats/side/lollipop_specs.png"),
	nerd_glasses: require("../assets/images/hats/side/nerd_glasses.png"),
	petal_specs: require("../assets/images/hats/side/petal_specs.png"),
	pixel_glasses: require("../assets/images/hats/side/pixel_glasses.png"),
	round_glasses: require("../assets/images/hats/side/round_glasses.png"),
	royal_pince_nez: require("../assets/images/hats/side/royal_pince_nez.png"),
	safety_goggles: require("../assets/images/hats/side/safety_goggles.png"),
	swim_goggles: require("../assets/images/hats/side/swim_goggles.png"),
	three_d_glasses: require("../assets/images/hats/side/three_d_glasses.png"),
	tophat: require("../assets/images/hats/side/tophat.png"),
	wallow_bronze_specs: require("../assets/images/hats/side/wallow_bronze_specs.png"),
	wizard: require("../assets/images/hats/side/wizard.png"),
};
