// AUTO-GENERATED by tools/gen_side_items.py — do not edit by hand.
// Rebuilt from assets/images/hats/side/ on every run: every item with a
// three-quarter sprite for the turned (`face` / `face_sit`) pig. An item
// missing here keeps its front sprite when the pig turns.

export const HAT_SIDE_IMAGES: Record<string, number> = {
	acorn_bow: require("../assets/images/hats/side/acorn_bow.png"),
	astronaut: require("../assets/images/hats/side/astronaut.png"),
	aviator_sunglasses: require("../assets/images/hats/side/aviator_sunglasses.png"),
	cowboy: require("../assets/images/hats/side/cowboy.png"),
	tophat: require("../assets/images/hats/side/tophat.png"),
	wizard: require("../assets/images/hats/side/wizard.png"),
};
