// AUTO-GENERATED by scripts/compute_overlays.py
// LEGACY items only — items with an anchor-relative RelSpec (the
// canonical model, tuned in tools/placement_studio) are skipped, as
// are full-canvas (aura/background) + tickle_particle categories.
// This file is the remaining legacy backlog: tune each in the studio
// to give it a RelSpec and it drops out of here automatically.

import { HatOverlay } from "./hat_overlay_types";

export const HAT_OVERLAYS_GENERATED: Record<string, HatOverlay> = {
};
