// AUTO-GENERATED by tools/item-anchor — do not edit by hand.
// The web tool writes this live as you drag attach points.
import type { RelSpec } from "./hat_overlay_types";

export const HAT_REL_DATA: Record<string, RelSpec> = {};
