#!/usr/bin/env python3
"""Local server for the item-anchor web tool.

Serves the repo statically so the tool + assets load, AND accepts
`POST /save` — the tool posts its full state and this writes
`constants/hat_rel.generated.ts`. So dragging an item's attach point
in the browser auto-persists into the app (Metro hot-reloads it) with
no copy-paste.

Run:  python3 tools/item-anchor/serve.py
Open: http://localhost:8123/tools/item-anchor/index.html
"""
import http.server
import json
import os
import socketserver

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
GEN = os.path.join(ROOT, "constants", "hat_rel.generated.ts")
PORT = 8123


def write_generated(data: dict) -> None:
    lines = []
    for item_id in sorted(data):
        s = data[item_id]
        p = s["pivot"]
        lines.append(
            "\t%s: { pivot: { x: %s, y: %s }, widthFrac: %s, "
            "anchor: \"%s\", behind: %s },"
            % (
                item_id,
                round(float(p["x"]), 4),
                round(float(p["y"]), 4),
                round(float(s["widthFrac"]), 4),
                s["anchor"],
                "true" if s.get("behind") else "false",
            )
        )
    body = (
        "// AUTO-GENERATED by tools/item-anchor — do not edit by hand.\n"
        "// The web tool writes this live as you drag attach points.\n"
        'import type { RelSpec } from "./hat_overlay_types";\n\n'
        "export const HAT_REL_DATA: Record<string, RelSpec> = {\n"
        + "\n".join(lines)
        + ("\n" if lines else "")
        + "};\n"
    )
    with open(GEN, "w") as f:
        f.write(body)


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=ROOT, **kwargs)

    def do_POST(self):
        if self.path != "/save":
            self.send_error(404)
            return
        try:
            n = int(self.headers.get("Content-Length", 0))
            data = json.loads(self.rfile.read(n) or b"{}")
            write_generated(data)
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(b'{"ok":true}')
        except Exception as exc:  # noqa: BLE001
            self.send_error(500, str(exc))

    def log_message(self, *args):
        pass  # quiet


if __name__ == "__main__":
    socketserver.ThreadingTCPServer.allow_reuse_address = True
    with socketserver.ThreadingTCPServer(("127.0.0.1", PORT), Handler) as httpd:
        print(f"item-anchor server → http://localhost:{PORT}/tools/item-anchor/index.html")
        httpd.serve_forever()
