const { withProjectBuildGradle } = require("expo/config-plugins");

const MARKER = "// @generated by withAndroidXCoreApi35";
const PIN = `${MARKER}
    // Expo SDK 52 uses AGP 8.6 / API 35. Newer transitive AndroidX Core
    // releases require API 36 + AGP 8.9, so keep this native dependency on
    // the newest API-35-compatible line until the Expo SDK upgrade.
    configurations.configureEach {
        resolutionStrategy.force(
            "androidx.core:core:1.16.0",
            "androidx.core:core-ktx:1.16.0"
        )
    }`;

module.exports = function withAndroidXCoreApi35(config) {
  return withProjectBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== "groovy") return gradleConfig;
    if (gradleConfig.modResults.contents.includes(MARKER)) return gradleConfig;

    gradleConfig.modResults.contents = gradleConfig.modResults.contents.replace(
      "allprojects {",
      `allprojects {\n${PIN}`,
    );
    return gradleConfig;
  });
};
