-- Harness-only stand-in for the production pg_net push helper. The focused
-- Feeding smoke records calls so it can assert routing and duplicate behavior
-- without making external HTTP requests.
CREATE TABLE IF NOT EXISTS public.smoke_push_calls (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	target_user_id uuid NOT NULL,
	push_title text NOT NULL,
	push_body text NOT NULL,
	push_data jsonb NOT NULL
);

CREATE OR REPLACE FUNCTION public.send_push_to_user(
	target_user_id uuid,
	push_title text,
	push_body text,
	push_data jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
	call_id bigint;
BEGIN
	INSERT INTO public.smoke_push_calls (
		target_user_id, push_title, push_body, push_data
	) VALUES (
		target_user_id, push_title, push_body, push_data
	)
	RETURNING id INTO call_id;

	RETURN jsonb_build_object('ok', true, 'request_id', call_id);
END;
$function$;

