#!/usr/bin/env python3
"""Auto-rigger for the pig sprite.

Scans each animation frame, detects anatomy points (eyes, snout, mouth,
ear tips, top-of-head, feet, hands), and prints out the values that
should replace REST_ANCHORS + PIG_FRAME_ANCHORS in constants/hats.ts.

Coordinates are converted to CARD space (300×300, y from top) which is
what the renderer uses. The conversion accounts for React Native's
`resizeMode=contain` math: the sprite frame (e.g. 370×383 px) gets
scaled to fit the 300×300 card preserving aspect ratio, with letter-
boxing on the smaller axis.

Detection heuristics:
- Eyes: two largest dark connected components in the upper 55% of the
  sprite, excluding the snout/mouth.
- Snout: largest connected region of "deeper pink" (#EF8FA4-ish, lower
  green/blue than body #F8B9C6).
- Mouth: small dark region BELOW the snout center, in a tight window.
- Ear tips: topmost opaque pixels on the left and right 1/3 bands.
- Head crown: topmost opaque pixel in the central 50%-width strip
  (between the ears).
- Feet: bottommost opaque pixel in the central horizontal band.
- Hand left/right: leftmost and rightmost opaque pixels at body height
  (rough — used as fallback if no finer detector is added).
"""
import os
import numpy as np
from PIL import Image
try:
    from scipy import ndimage
except ImportError:
    raise SystemExit("scipy is required: pip install scipy")

SPRITE_DIR = "/Users/bbroeking/projects/oink/assets/images/sprites/rosie"
CARD_SIZE = 300

# 4 frames per animation. Generated by slicer; idle_1 is the canonical
# reference for REST_ANCHORS.
ANIMATIONS = ["idle", "walk", "jump", "happy", "sad", "surprise", "wave"]


# ── Coordinate conversion ───────────────────────────────────────
def fit_contain(sw: int, sh: int, card: int = CARD_SIZE):
    """React Native resizeMode=contain: largest scale that fits both
    dimensions inside the card while preserving aspect ratio."""
    scale = min(card / sw, card / sh)
    rendered_w = sw * scale
    rendered_h = sh * scale
    x_off = (card - rendered_w) / 2
    y_off = (card - rendered_h) / 2
    return scale, x_off, y_off


def px_to_card(py: float, px: float, sprite_shape):
    """Sprite-pixel (y, x) → card (y, x) — y from TOP, matching hats.ts."""
    sh, sw = sprite_shape[:2]
    scale, x_off, y_off = fit_contain(sw, sh)
    return round(y_off + py * scale), round(x_off + px * scale)


# ── Pixel-level detectors ───────────────────────────────────────
def load_rgba(path: str) -> np.ndarray:
    return np.array(Image.open(path).convert("RGBA"))


def _largest_centroids(mask: np.ndarray, k: int):
    """Return (cy, cx, size) for the k largest connected components."""
    labeled, n = ndimage.label(mask)
    if n == 0:
        return []
    sizes = ndimage.sum(mask, labeled, range(1, n + 1))
    order = np.argsort(sizes)[::-1][:k]
    out = []
    for i in order:
        lbl = i + 1
        cy, cx = ndimage.center_of_mass(mask, labeled, lbl)
        out.append((cy, cx, sizes[i]))
    return out


def detect_eyes(arr: np.ndarray):
    """Two largest dark components in the upper 55%. Eyes are pure-black
    in this art style with small white highlights — luminance very low."""
    h, w = arr.shape[:2]
    upper = arr[: int(h * 0.55)]
    lum = 0.299 * upper[:, :, 0] + 0.587 * upper[:, :, 1] + 0.114 * upper[:, :, 2]
    alpha = upper[:, :, 3]
    dark = (lum < 50) & (alpha > 100)
    cands = _largest_centroids(dark, k=8)
    # Filter by size — eyes have characteristic ~200-2000 px area at this resolution.
    # Drop ear-edge noise and tiny outline kinks.
    cands = [c for c in cands if c[2] > 50]
    if len(cands) < 2:
        return None
    # Pick the two near the SAME vertical band (delta_y small) to avoid
    # mistaking the snout or nostrils for an eye.
    best = None
    best_score = 1e9
    for i in range(len(cands)):
        for j in range(i + 1, len(cands)):
            a, b = cands[i], cands[j]
            dy = abs(a[0] - b[0])
            dx = abs(a[1] - b[1])
            # Two eyes share a y-line and are horizontally separated.
            if dy < 30 and dx > 40:
                score = dy + abs(dx - 100)  # prefer pairs ~100px apart
                if score < best_score:
                    best_score = score
                    best = (a, b)
    if not best:
        return None
    a, b = sorted(best, key=lambda c: c[1])  # left, right
    return (a[0], a[1]), (b[0], b[1])


def detect_snout(arr: np.ndarray):
    """Pinker than body — #EF8FA4 vs #F8B9C6. Look for the connected
    region whose color satisfies R∈[210, 250], G∈[110, 170], B∈[140, 185]."""
    r, g, b, a = arr[:, :, 0], arr[:, :, 1], arr[:, :, 2], arr[:, :, 3]
    snout = (
        (r > 210) & (r < 252)
        & (g > 100) & (g < 175)
        & (b > 130) & (b < 195)
        & (a > 100)
    )
    cands = _largest_centroids(snout, k=3)
    cands = [c for c in cands if c[2] > 200]
    if not cands:
        return None
    # Pick the candidate closest to the horizontal center (snout is on
    # midline) and in the upper 60% (above the chest).
    h, w = arr.shape[:2]
    mid_x = w / 2
    cands.sort(key=lambda c: abs(c[1] - mid_x) + max(0, c[0] - h * 0.6) * 2)
    cy, cx, _ = cands[0]
    return cy, cx


def detect_mouth(arr: np.ndarray, snout_yx):
    """Small dark region immediately below the snout."""
    if not snout_yx:
        return None
    sy, sx = snout_yx
    h, w = arr.shape[:2]
    # Search window: 0-60 px below snout, 80 px wide.
    y0 = int(sy)
    y1 = min(h, int(sy) + 70)
    x0 = max(0, int(sx) - 50)
    x1 = min(w, int(sx) + 50)
    region = arr[y0:y1, x0:x1]
    if region.size == 0:
        return None
    lum = 0.299 * region[:, :, 0] + 0.587 * region[:, :, 1] + 0.114 * region[:, :, 2]
    alpha = region[:, :, 3]
    dark = (lum < 80) & (alpha > 100)
    cands = _largest_centroids(dark, k=3)
    cands = [c for c in cands if c[2] > 30]
    if not cands:
        return None
    cy, cx, _ = cands[0]
    return y0 + cy, x0 + cx


def detect_head_crown(arr: np.ndarray):
    """Topmost opaque pixel in the central 50% horizontal band.
    The central band excludes ear tips that stick out higher."""
    h, w = arr.shape[:2]
    alpha = arr[:, :, 3]
    band_x0, band_x1 = int(w * 0.30), int(w * 0.70)
    band = alpha[:, band_x0:band_x1]
    rows = np.any(band > 50, axis=1)
    if not rows.any():
        return None
    top = int(np.argmax(rows))
    # x = center of opaque pixels on that row
    row_alpha = arr[top, band_x0:band_x1, 3]
    xs = np.where(row_alpha > 50)[0]
    if len(xs) == 0:
        return None
    cx = band_x0 + (xs.min() + xs.max()) / 2
    return float(top), float(cx)


def detect_ears(arr: np.ndarray):
    """Ear tips: topmost opaque pixel on the LEFT and RIGHT side bands."""
    h, w = arr.shape[:2]
    alpha = arr[:, :, 3]

    def topmost(x0: int, x1: int):
        band = alpha[:, x0:x1]
        rows = np.any(band > 50, axis=1)
        if not rows.any():
            return None
        ty = int(np.argmax(rows))
        row = arr[ty, x0:x1, 3]
        xs = np.where(row > 50)[0]
        if len(xs) == 0:
            return None
        return float(ty), float(x0 + (xs.min() + xs.max()) / 2)

    return topmost(0, int(w * 0.35)), topmost(int(w * 0.65), w)


def detect_feet(arr: np.ndarray):
    """Bottommost opaque pixel in the central horizontal band."""
    h, w = arr.shape[:2]
    alpha = arr[:, :, 3]
    band_x0, band_x1 = int(w * 0.20), int(w * 0.80)
    band = alpha[:, band_x0:band_x1]
    rows = np.any(band > 50, axis=1)
    if not rows.any():
        return None
    bot = int(np.where(rows)[0].max())
    row_alpha = arr[bot, band_x0:band_x1, 3]
    xs = np.where(row_alpha > 50)[0]
    if len(xs) == 0:
        return None
    cx = band_x0 + (xs.min() + xs.max()) / 2
    return float(bot), float(cx)


def _content_bbox(arr: np.ndarray):
    """Bounding box of all opaque content: (y0, y1, x0, x1)."""
    alpha = arr[:, :, 3]
    mask = alpha > 50
    if not mask.any():
        return None
    ys, xs = np.where(mask)
    return int(ys.min()), int(ys.max()), int(xs.min()), int(xs.max())


# ── Per-frame anatomy bundle ────────────────────────────────────
def detect_all(path: str):
    arr = load_rgba(path)
    sh, sw = arr.shape[:2]
    eyes = detect_eyes(arr)
    if eyes:
        eyes_yx = ((eyes[0][0] + eyes[1][0]) / 2, (eyes[0][1] + eyes[1][1]) / 2)
    else:
        eyes_yx = None
    snout = detect_snout(arr)
    mouth = detect_mouth(arr, snout)
    head = detect_head_crown(arr)
    ears = detect_ears(arr)
    feet = detect_feet(arr)

    def to_card(yx):
        if yx is None:
            return None
        cy, cx = px_to_card(yx[0], yx[1], arr.shape)
        return {"x": cx, "y": cy}

    # neck = halfway between snout and feet, body = a bit below neck.
    # (Fixed from earlier bug where `(snout + feet) * 0.65` over-shot
    # past the feet — must INTERPOLATE between them, not scale their sum.)
    neck_yx = None
    body_yx = None
    if snout and feet:
        s_y, s_x = snout
        f_y, _ = feet
        neck_yx = (s_y + 0.55 * (f_y - s_y), s_x)
        body_yx = (s_y + 0.70 * (f_y - s_y), s_x)

    # Hand positions: use bbox center + a fixed inset from the bbox edges
    # rather than leftmost/rightmost opaque pixel (which lands on ear tips
    # or body silhouette, not the actual hand). The pig art has front
    # hands roughly at 25% / 75% of body width.
    bbox = _content_bbox(arr)
    hand_l_yx = None
    hand_r_yx = None
    if bbox and snout:
        by0, by1, bx0, bx1 = bbox
        bw = bx1 - bx0
        # Hand y: about 75% down the body (below the chest line).
        hand_y = snout[0] + 0.35 * (bbox[1] - snout[0])
        hand_l_yx = (hand_y, bx0 + bw * 0.20)
        hand_r_yx = (hand_y, bx0 + bw * 0.80)

    return {
        "head": to_card(head),
        "eyes": to_card(eyes_yx),
        "ear_l": to_card(ears[0]) if ears else None,
        "ear_r": to_card(ears[1]) if ears else None,
        "snout": to_card(snout),
        "mouth": to_card(mouth),
        "neck": to_card(neck_yx),
        "body": to_card(body_yx),
        "hand_l": to_card(hand_l_yx),
        "hand_r": to_card(hand_r_yx),
        "feet": to_card(feet),
    }


# ── Top-level: scan every frame, emit TS-ready constants ────────
CENTERLINE_ANCHORS = {"head", "eyes", "snout", "mouth", "neck", "body", "feet"}


def normalize_rest(rest):
    """Force centerline anchors to x=150 so items render on the pig's
    midline regardless of where the detector found the pixel centroid.
    Without this, an asymmetric pose (e.g. one hand extended) skews
    every "should-be-centered" anchor by a few px and items drift."""
    out = dict(rest)
    for k in CENTERLINE_ANCHORS:
        v = out.get(k)
        if v is None:
            continue
        out[k] = {"x": 150, "y": v["y"]}
    return out


def main():
    rest_raw = detect_all(os.path.join(SPRITE_DIR, "idle_1.png"))
    rest = normalize_rest(rest_raw)

    print("/* ── Auto-generated by scripts/auto_rig.py ─────────────────── */")
    print("// REST_ANCHORS — detected from idle_1.png.")
    print("// Centerline anchors (head/snout/mouth/neck/body/feet) snapped")
    print("// to x=150 so items render on the pig's midline regardless of")
    print("// per-pose asymmetry.\n")
    print("const REST_ANCHORS: Record<AnchorName, Anchor> = {")
    for k in ["head", "eyes", "snout", "mouth", "neck", "body",
              "hand_l", "hand_r", "feet"]:
        v = rest.get(k)
        if v is None:
            print(f"\t{k}: {{ x: 150, y: 150 }}, // !! detection failed — fallback")
        else:
            print(f"\t{k}: {{ x: {v['x']}, y: {v['y']} }},")
    print("};\n")

    # Per-frame deltas: detect the FEET y of each frame and compute a
    # bulk vertical shift (negative = pig moved up). This is much more
    # robust than per-anchor centroid diffs, which were noisy with
    # detector false positives. The shiftAll(dy) helper applies the
    # bulk shift uniformly to every anchor at render time.
    print("// PIG_FRAME_ANCHORS — derived from per-frame FEET position")
    print("// vs idle_1. Bulk vertical shift only; we rely on shiftAll()")
    print("// rather than per-anchor centroids to avoid detector noise.\n")
    print("export const PIG_FRAME_ANCHORS: Record<")
    print("\tPigAnimationKey,")
    print("\tPartial<Record<AnchorName, Anchor>>[]")
    print("> = {")

    rest_feet_y = rest_raw["feet"]["y"] if rest_raw.get("feet") else None
    for anim in ANIMATIONS:
        print(f"\t{anim}: [")
        for i in range(1, 5):
            frame_path = os.path.join(SPRITE_DIR, f"{anim}_{i}.png")
            if not os.path.exists(frame_path) or rest_feet_y is None:
                print("\t\t{}, // (rest)")
                continue
            det_raw = detect_all(frame_path)
            f = det_raw.get("feet")
            if not f:
                print("\t\t{}, // (no feet detected — rest)")
                continue
            dy = f["y"] - rest_feet_y
            # Snap small deltas to zero so subtle detector wobble doesn't
            # show up as frame jitter at runtime.
            if abs(dy) < 4:
                print("\t\t{}, // (rest)")
            else:
                print(f"\t\tshiftAll({dy}),")
        print("\t],")
    print("};")


if __name__ == "__main__":
    main()
