#!/usr/bin/env node
/**
 * Regenerate the members-only catalog artifacts from docs/members-catalog.json:
 *   - supabase/migrations/20260690000000_seed_members_catalog.sql  (hats rows)
 *   - constants/membersFx.generated.ts                              (id -> {category,theme})
 *   - docs/members-only-catalog-final.md                           (art worksheet)
 *
 * Idempotent. Worksheet checkboxes are derived from whether the item's PNG
 * exists in assets/images/hats/, so re-running always reflects true progress.
 * display_order is 1001 + index (the Signet Crown is 1000).
 *
 * Usage: node scripts/gen_members_catalog.js
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const items = JSON.parse(
  fs.readFileSync(path.join(ROOT, "docs/members-catalog.json"), "utf8")
);
const sq = (s) => String(s).replace(/'/g, "''");
const hasArt = (id) =>
  fs.existsSync(path.join(ROOT, `assets/images/hats/${id}.png`)) ||
  fs.existsSync(path.join(ROOT, `assets/images/backgrounds/${id}.png`)) ||
  fs.existsSync(path.join(ROOT, `assets/images/backgrounds/${id}_1.png`));

// 1) seed migration
const rows = items
  .map((it, idx) => {
    const ord = 1001 + idx;
    return `\t('${it.id}', '${sq(it.name)}', NULL, ${it.cost}, ${ord}, '${it.category}', '${it.rarity}', '${sq(it.description)}', true)`;
  })
  .join(",\n");
const sql = `-- Slop Club members-only catalog seed — ${items.length} items (build-100).
-- AUTO-GENERATED by scripts/gen_members_catalog.js from docs/members-catalog.json.
-- All ids are collision-checked against every existing hats id; categories are
-- placeable only (no cape/necklace/scarf); cost follows the members ladder
-- (common 1200/uncommon 2000/rare 3000/epic 4200/legendary 5500); members_only
-- =true so daily_shop() never rolls them and buy_hat() gates them to members.
-- Art is generated separately (ChatGPT cozy-sticker pipeline) and keyed into
-- constants/hats.ts as each PNG lands; the shop hides any members item without
-- art, so this seed is safe to apply before all images exist. Animation is
-- automatic via constants/cosmeticFx.ts (theme x category archetype).
-- emoji NULL on purpose (real art, no legacy fallback glyph).

INSERT INTO public.hats
\t(id, name, emoji, cost, display_order, category, rarity, description, members_only)
VALUES
${rows}
ON CONFLICT (id) DO UPDATE SET
\tname          = EXCLUDED.name,
\tcost          = EXCLUDED.cost,
\tdisplay_order = EXCLUDED.display_order,
\tcategory      = EXCLUDED.category,
\trarity        = EXCLUDED.rarity,
\tdescription   = EXCLUDED.description,
\tmembers_only  = EXCLUDED.members_only;
`;
fs.writeFileSync(
  path.join(ROOT, "supabase/migrations/20260690000000_seed_members_catalog.sql"),
  sql
);

// 2) FX registry
const reg = items
  .map((it) => `\t${it.id}: { category: "${it.category}", theme: ${JSON.stringify(it.theme)} },`)
  .join("\n");
fs.writeFileSync(
  path.join(ROOT, "constants/membersFx.generated.ts"),
  `// AUTO-GENERATED by scripts/gen_members_catalog.js — do not hand-edit.
// Maps each members-only item id to its (category, theme) so cosmeticFx.ts can
// derive a per-item animation recipe (theme accent x category sparkle layout).
export const MEMBERS_FX_DATA: Record<string, { category: string; theme: string }> = {
${reg}
};
`
);

// 3) anchor-relative placement defaults (the path that actually fits on the
// pig — see PigStage.resolveSlot). Derived from the hand-tuned hat_rel.generated
// patterns: hats sit bottom-on-crown, glasses/masks center on the eyes, held
// items grip at the hand. auras (full-canvas), backgrounds, and tickle_particles
// are NOT worn on the pig body, so they get no rel entry. Any item can later be
// hand-tuned in tools/item-anchor; that entry (in hat_rel.generated.ts) wins.
const CATEGORY_REL = {
  hat:     { px: 0.5,  py: 0.86, wf: 0.42, anchor: "head" },
  bow:     { px: 0.46, py: 0.5,  wf: 0.42, anchor: "head" },
  glasses: { px: 0.49, py: 0.52, wf: 0.62, anchor: "eyes" },
  mask:    { px: 0.49, py: 0.66, wf: 0.62, anchor: "eyes" },
  held:    { px: 0.45, py: 0.72, wf: 0.42, anchor: "hand_r" },
};
const relLines = items
  .filter((it) => CATEGORY_REL[it.category])
  .map((it) => {
    const c = CATEGORY_REL[it.category];
    return `\t${it.id}: { pivot: { x: ${c.px}, y: ${c.py} }, widthFrac: ${c.wf}, anchor: "${c.anchor}", behind: false },`;
  })
  .join("\n");
fs.writeFileSync(
  path.join(ROOT, "constants/membersRel.generated.ts"),
  `// AUTO-GENERATED by scripts/gen_members_catalog.js — do not hand-edit.
// Category-default anchor-relative placement for members items so they sit on
// the pig (PigStage.resolveSlot). Merged UNDER hat_rel.generated (hand-tuned
// entries win). Tune any item precisely via tools/item-anchor.
import type { RelSpec } from "./hat_overlay_types";
export const MEMBERS_REL_DATA: Record<string, RelSpec> = {
${relLines}
};
`
);

// 4) auto-wire HAT_IMAGES — require() for every item whose art has landed
// (hats/<id>.png, or backgrounds/<id>.png or _1.png for animated bgs). Spread
// into HAT_IMAGES so each generated batch wires itself; no manual edits.
const imgLines = items
  .map((it) => {
    const hat = `assets/images/hats/${it.id}.png`;
    const bg = `assets/images/backgrounds/${it.id}.png`;
    const bg1 = `assets/images/backgrounds/${it.id}_1.png`;
    if (fs.existsSync(path.join(ROOT, hat)))
      return `\t${it.id}: require("../${hat}"),`;
    if (fs.existsSync(path.join(ROOT, bg)))
      return `\t${it.id}: require("../${bg}"),`;
    if (fs.existsSync(path.join(ROOT, bg1)))
      return `\t${it.id}: require("../${bg1}"),`; // animated bg → frame 1 thumbnail
    return null;
  })
  .filter(Boolean)
  .join("\n");
fs.writeFileSync(
  path.join(ROOT, "constants/membersImages.generated.ts"),
  `// AUTO-GENERATED by scripts/gen_members_catalog.js — do not hand-edit.
// require() map for members-only art that has been generated. Spread into
// HAT_IMAGES in constants/hats.ts. Re-run the generator after adding art.
export const MEMBERS_IMAGES: Record<string, number> = {
${imgLines}
};
`
);

// 5) worksheet (checkbox = PNG exists)
const byTheme = {};
items.forEach((it, idx) => ((byTheme[it.theme] ??= []).push({ ...it, ord: 1001 + idx })));
let md = `# Slop Club members-only catalog — FINAL (${items.length} items)\n\n`;
md += `AUTO-GENERATED by scripts/gen_members_catalog.js from docs/members-catalog.json.\n`;
md += `Checkbox = art exists in assets/images/hats/. Seed: \`supabase/migrations/20260690000000_seed_members_catalog.sql\`.\n\n`;
md += `**Per item:** paste the prompt into ChatGPT image-gen -> download -> \`python3 scripts/process_cosmetic.py <download> <id>\` -> add \`<id>: require(...)\` to HAT_IMAGES.\n\n`;
let n = 0,
  done = 0;
for (const th of Object.keys(byTheme)) {
  md += `## ${th}\n\n`;
  for (const it of byTheme[th]) {
    n++;
    const x = hasArt(it.id);
    if (x) done++;
    md += `### [${x ? "x" : " "}] ${n}. ${it.name} — \`${it.id}\` (${it.category}, ${it.rarity}, ${it.cost})\n`;
    md += `> ${it.description}\n\n`;
    md += `\`\`\`\n${it.chatgpt_prompt}\n\`\`\`\n\n`;
  }
}
fs.writeFileSync(path.join(ROOT, "docs/members-only-catalog-final.md"), md);

console.log(`regenerated: ${items.length} items, ${done} have art, ${items.length - done} remaining`);
