#!/usr/bin/env node
// The web lane of the taste standard (docs/design/taste-standard.md,
// design-system-spec §3 rule 7). Two gates:
//
//   1. No emoji in the web UI ("no emoji in UI, ever" reaches past the app).
//   2. tokens.css + sticker.css are in sync with constants/theme.ts — in web/
//      (canonical) and in every served copy (landing/, analytics-dashboard/app/).
//      A theme edit without a rebuild is caught here, not in review.
//
//   npm run lint:web        → prints file:line: <snippet>, exits 1 on any hit.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));

// landing/den and landing/plan are password-gated founder tools (plan is
// generated by tools/build_roadmap.mjs and uses emoji as a status legend);
// they are not player-facing UI, so the gate stops at the public pages.
const TARGETS = [
  {
    dir: "landing",
    exts: [".html"],
    skip: ["landing/mocks", "landing/labs", "landing/den", "landing/plan"],
  },
  { dir: "analytics-dashboard/app", exts: [".js", ".css"], skip: [] },
];

const ALWAYS_SKIP = new Set(["node_modules", ".git", ".next", "dist", "build"]);

// Astral emoji planes + U+2600–U+27BF, minus ★ U+2605, ♥ U+2665, ✓ U+2713,
// ✕ U+2715, ✦ U+2726, ✧ U+2727. Keep in sync with EMOJI_RE in .eslintrc.js.
const EMOJI =
  /(\uD83C[\uDF00-\uDFFF]|\uD83D[\uDC00-\uDE4F]|\uD83E[\uDD00-\uDEFF]|[\u2600-\u2604\u2606-\u2664\u2666-\u2712\u2714\u2716-\u2725\u2728-\u27BF])/;

function* walk(dir, skip) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    const rel = relative(ROOT, full).split(sep).join("/");
    if (skip.some((s) => rel === s || rel.startsWith(`${s}/`))) continue;
    if (entry.isDirectory()) {
      if (ALWAYS_SKIP.has(entry.name)) continue;
      yield* walk(full, skip);
    } else if (entry.isFile()) {
      yield full;
    }
  }
}

// ----------------------------------------------------------------- 1. emoji --

const hits = [];
for (const target of TARGETS) {
  const base = join(ROOT, target.dir);
  try {
    if (!statSync(base).isDirectory()) continue;
  } catch {
    continue;
  }
  for (const file of walk(base, target.skip)) {
    if (!target.exts.some((ext) => file.endsWith(ext))) continue;
    const rel = relative(ROOT, file).split(sep).join("/");
    const lines = readFileSync(file, "utf8").split(/\r?\n/);
    lines.forEach((line, i) => {
      if (!EMOJI.test(line)) return;
      const col = line.search(EMOJI);
      const snippet = line.slice(Math.max(0, col - 40), col + 40).trim();
      hits.push(`${rel}:${i + 1}: ${snippet}`);
    });
  }
}

// ----------------------------------------------- 2. generated token freshness --

// Regenerate into a scratch dir and diff. Cheap (one esbuild transform), and it
// is the only way to notice that someone edited theme.ts and not web/.
const GENERATED = ["tokens.css", "sticker.css"];
// web/ is canonical; the served copies must match it byte for byte (a page can
// only <link> a stylesheet that lives inside its own deploy root).
const GENERATED_TREES = ["web", "landing", "analytics-dashboard/app"];
const stale = [];
const scratch = mkdtempSync(join(tmpdir(), "ttp-web-tokens-"));
try {
  execFileSync(process.execPath, [join(ROOT, "scripts", "build-web-tokens.mjs"), "--out", scratch], {
    cwd: ROOT,
    stdio: ["ignore", "ignore", "inherit"],
  });
  for (const name of GENERATED) {
    const fresh = readFileSync(join(scratch, name), "utf8");
    for (const tree of GENERATED_TREES) {
      let current = null;
      try {
        current = readFileSync(join(ROOT, tree, name), "utf8");
      } catch {
        stale.push(`${tree}/${name} is missing`);
        continue;
      }
      if (current !== fresh) stale.push(`${tree}/${name} is stale`);
    }
  }
} finally {
  rmSync(scratch, { recursive: true, force: true });
}

// ---------------------------------------------------------------- reporting --

let failed = false;

if (hits.length) {
  failed = true;
  for (const hit of hits) console.log(hit);
  console.error(
    `\n${hits.length} emoji ${hits.length === 1 ? "hit" : "hits"} in web UI. Use an inline SVG or the hand-drawn art instead (docs/design/taste-standard.md).`,
  );
}

if (stale.length) {
  failed = true;
  for (const s of stale) console.log(s);
  console.error(
    `\nThe generated web token layer no longer matches constants/theme.ts. Run \`npm run build:tokens\` and commit the result.`,
  );
}

if (failed) process.exit(1);

console.log(
  "lint:web — no emoji in the web surfaces; tokens.css + sticker.css match constants/theme.ts in web/, landing/ and analytics-dashboard/app/.",
);
