create table "public"."counters" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "count" bigint default '0'::bigint
);


alter table "public"."counters" enable row level security;

create table "public"."user_items" (
    "user_id" uuid not null,
    "item_count" integer default 0,
    "last_increment" timestamp without time zone default CURRENT_TIMESTAMP
);


alter table "public"."user_items" enable row level security;

alter table "public"."profiles" add column "counter" bigint not null default '0'::bigint;

CREATE UNIQUE INDEX counters_pkey ON public.counters USING btree (id);

CREATE UNIQUE INDEX user_items_pkey ON public.user_items USING btree (user_id);

alter table "public"."counters" add constraint "counters_pkey" PRIMARY KEY using index "counters_pkey";

alter table "public"."user_items" add constraint "user_items_pkey" PRIMARY KEY using index "user_items_pkey";

alter table "public"."user_items" add constraint "user_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_items" validate constraint "user_items_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.increment_counter(user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE profiles
    SET counter = counter + 1
    WHERE id = user_id;  -- Use the parameter name here
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_user_items()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE user_items
  SET item_count = LEAST(item_count + 1, 10),
      last_increment = CURRENT_TIMESTAMP
  WHERE CURRENT_TIMESTAMP - last_increment >= INTERVAL '1 hour';
END;
$function$
;

grant delete on table "public"."counters" to "anon";

grant insert on table "public"."counters" to "anon";

grant references on table "public"."counters" to "anon";

grant select on table "public"."counters" to "anon";

grant trigger on table "public"."counters" to "anon";

grant truncate on table "public"."counters" to "anon";

grant update on table "public"."counters" to "anon";

grant delete on table "public"."counters" to "authenticated";

grant insert on table "public"."counters" to "authenticated";

grant references on table "public"."counters" to "authenticated";

grant select on table "public"."counters" to "authenticated";

grant trigger on table "public"."counters" to "authenticated";

grant truncate on table "public"."counters" to "authenticated";

grant update on table "public"."counters" to "authenticated";

grant delete on table "public"."counters" to "service_role";

grant insert on table "public"."counters" to "service_role";

grant references on table "public"."counters" to "service_role";

grant select on table "public"."counters" to "service_role";

grant trigger on table "public"."counters" to "service_role";

grant truncate on table "public"."counters" to "service_role";

grant update on table "public"."counters" to "service_role";

grant delete on table "public"."user_items" to "anon";

grant insert on table "public"."user_items" to "anon";

grant references on table "public"."user_items" to "anon";

grant select on table "public"."user_items" to "anon";

grant trigger on table "public"."user_items" to "anon";

grant truncate on table "public"."user_items" to "anon";

grant update on table "public"."user_items" to "anon";

grant delete on table "public"."user_items" to "authenticated";

grant insert on table "public"."user_items" to "authenticated";

grant references on table "public"."user_items" to "authenticated";

grant select on table "public"."user_items" to "authenticated";

grant trigger on table "public"."user_items" to "authenticated";

grant truncate on table "public"."user_items" to "authenticated";

grant update on table "public"."user_items" to "authenticated";

grant delete on table "public"."user_items" to "service_role";

grant insert on table "public"."user_items" to "service_role";

grant references on table "public"."user_items" to "service_role";

grant select on table "public"."user_items" to "service_role";

grant trigger on table "public"."user_items" to "service_role";

grant truncate on table "public"."user_items" to "service_role";

grant update on table "public"."user_items" to "service_role";


