-- Corrective rescale — restore per-item price granularity after the
-- 20260546 clamp.
--
-- What went wrong: 20260533_reduce_prices.sql had already divided
-- every price by 10 (3-10 / 10-40 / 40-150 / etc.). Then
-- 20260546_economy_rebalance.sql clamped into bands much higher than
-- the post-/10 numbers, so GREATEST(band_min, …) floored every
-- common to 100, every uncommon to 200, etc. — total loss of
-- per-item variation inside each rarity.
--
-- Fix: rescale each item proportionally from its ORIGINAL seed price
-- (from 20260502030000_shop_catalog.sql + 20260501210000_hats_shop.sql)
-- into the new band. Formula per item:
--
--   new_cost = round( new_min
--                   + (old - rarity_old_min)
--                   / (rarity_old_max - rarity_old_min)
--                   * (new_max - new_min) )
--
-- Source-of-truth bands (from the original seeds, by rarity):
--   common     25-200    → 100-200
--   uncommon   180-480   → 200-400
--   rare       500-1400  → 400-800
--   epic       1500-8000 → 800-2000
--   legendary  5000-6500 → 2000-5000
--
-- Generated by parsing the seed migrations + applying the formula
-- (see commit message for the generator script).
--
-- Season-pass exclusives (cost = 0) are untouched — they're filtered
-- out of the buy paths in 20260544_season_pass_missing_hats.sql.

UPDATE public.hats SET cost = 120 WHERE id = 'beanie';
UPDATE public.hats SET cost = 2000 WHERE id = 'crown';
UPDATE public.hats SET cost = 711 WHERE id = 'halo';
UPDATE public.hats SET cost = 313 WHERE id = 'pirate_tricorn';
UPDATE public.hats SET cost = 200 WHERE id = 'chef_toque';
UPDATE public.hats SET cost = 444 WHERE id = 'viking_helmet';
UPDATE public.hats SET cost = 131 WHERE id = 'round_glasses';
UPDATE public.hats SET cost = 213 WHERE id = 'aviator_sunglasses';
UPDATE public.hats SET cost = 711 WHERE id = 'monocle';
UPDATE public.hats SET cost = 137 WHERE id = 'swim_goggles';
UPDATE public.hats SET cost = 129 WHERE id = 'nerd_glasses';
UPDATE public.hats SET cost = 154 WHERE id = 'three_d_glasses';
UPDATE public.hats SET cost = 227 WHERE id = 'heart_sunglasses';
UPDATE public.hats SET cost = 313 WHERE id = 'pixel_glasses';
UPDATE public.hats SET cost = 120 WHERE id = 'safety_goggles';
UPDATE public.hats SET cost = 855 WHERE id = 'vr_headset';
UPDATE public.hats SET cost = 109 WHERE id = 'pink_bow';
UPDATE public.hats SET cost = 247 WHERE id = 'black_bow_tie';
UPDATE public.hats SET cost = 137 WHERE id = 'ribbon_bow';
UPDATE public.hats SET cost = 123 WHERE id = 'hair_bow';
UPDATE public.hats SET cost = 149 WHERE id = 'gift_bow';
UPDATE public.hats SET cost = 800 WHERE id = 'archery_bow';
UPDATE public.hats SET cost = 293 WHERE id = 'silk_bow';
UPDATE public.hats SET cost = 140 WHERE id = 'polka_bow';
UPDATE public.hats SET cost = 267 WHERE id = 'velvet_bow';
UPDATE public.hats SET cost = 667 WHERE id = 'rainbow_bow';
UPDATE public.hats SET cost = 126 WHERE id = 'knit_scarf';
UPDATE public.hats SET cost = 313 WHERE id = 'silk_scarf';
UPDATE public.hats SET cost = 117 WHERE id = 'bandana_red';
UPDATE public.hats SET cost = 227 WHERE id = 'cape_scarf';
UPDATE public.hats SET cost = 140 WHERE id = 'striped_scarf';
UPDATE public.hats SET cost = 154 WHERE id = 'winter_scarf';
UPDATE public.hats SET cost = 120 WHERE id = 'summer_kerchief';
UPDATE public.hats SET cost = 400 WHERE id = 'ascot';
UPDATE public.hats SET cost = 134 WHERE id = 'neckwarmer';
UPDATE public.hats SET cost = 711 WHERE id = 'rainbow_scarf';
UPDATE public.hats SET cost = 400 WHERE id = 'pink_glow';
UPDATE public.hats SET cost = 800 WHERE id = 'gold_aura';
UPDATE public.hats SET cost = 2000 WHERE id = 'rainbow_aura';
UPDATE public.hats SET cost = 756 WHERE id = 'fire_aura';
UPDATE public.hats SET cost = 756 WHERE id = 'ice_aura';
UPDATE public.hats SET cost = 800 WHERE id = 'electric_aura';
UPDATE public.hats SET cost = 929 WHERE id = 'shadow_aura';
UPDATE public.hats SET cost = 966 WHERE id = 'holy_aura';
UPDATE public.hats SET cost = 489 WHERE id = 'sparkle_aura';
UPDATE public.hats SET cost = 578 WHERE id = 'petal_aura';
UPDATE public.hats SET cost = 333 WHERE id = 'masquerade';
UPDATE public.hats SET cost = 154 WHERE id = 'domino';
UPDATE public.hats SET cost = 213 WHERE id = 'robber_mask';
UPDATE public.hats SET cost = 114 WHERE id = 'sleep_mask';
UPDATE public.hats SET cost = 667 WHERE id = 'gas_mask';
UPDATE public.hats SET cost = 293 WHERE id = 'carnival_mask';
UPDATE public.hats SET cost = 855 WHERE id = 'venice_mask';
UPDATE public.hats SET cost = 240 WHERE id = 'cat_mask';
UPDATE public.hats SET cost = 818 WHERE id = 'skull_mask';
UPDATE public.hats SET cost = 320 WHERE id = 'hero_mask';
UPDATE public.hats SET cost = 929 WHERE id = 'royal_cape';
UPDATE public.hats SET cost = 667 WHERE id = 'vampire_cape';
UPDATE public.hats SET cost = 800 WHERE id = 'hero_cape';
UPDATE public.hats SET cost = 489 WHERE id = 'magician_cape';
UPDATE public.hats SET cost = 400 WHERE id = 'fur_cape';
UPDATE public.hats SET cost = 333 WHERE id = 'silk_cape';
UPDATE public.hats SET cost = 293 WHERE id = 'leather_cape';
UPDATE public.hats SET cost = 227 WHERE id = 'short_cape';
UPDATE public.hats SET cost = 1354 WHERE id = 'ermine_cape';
UPDATE public.hats SET cost = 5000 WHERE id = 'star_cape';
UPDATE public.hats SET cost = 267 WHERE id = 'pearl_necklace';
UPDATE public.hats SET cost = 444 WHERE id = 'gold_chain';
UPDATE public.hats SET cost = 293 WHERE id = 'locket';
UPDATE public.hats SET cost = 189 WHERE id = 'bone_necklace';
UPDATE public.hats SET cost = 227 WHERE id = 'charm_necklace';
UPDATE public.hats SET cost = 1262 WHERE id = 'diamond_pendant';
UPDATE public.hats SET cost = 1169 WHERE id = 'emerald_pendant';
UPDATE public.hats SET cost = 149 WHERE id = 'choker';
UPDATE public.hats SET cost = 129 WHERE id = 'bell_collar';
UPDATE public.hats SET cost = 120 WHERE id = 'ribbon_choker';
UPDATE public.hats SET cost = 533 WHERE id = 'magic_wand';
UPDATE public.hats SET cost = 247 WHERE id = 'toy_sword';
UPDATE public.hats SET cost = 103 WHERE id = 'pencil';
UPDATE public.hats SET cost = 160 WHERE id = 'magnifier';
UPDATE public.hats SET cost = 111 WHERE id = 'balloon';
UPDATE public.hats SET cost = 189 WHERE id = 'flowers';
UPDATE public.hats SET cost = 123 WHERE id = 'ice_cream';
UPDATE public.hats SET cost = 131 WHERE id = 'pizza_slice';
UPDATE public.hats SET cost = 114 WHERE id = 'coffee_mug';
UPDATE public.hats SET cost = 313 WHERE id = 'controller';
UPDATE public.hats SET cost = 444 WHERE id = 'sunset_farm';
UPDATE public.hats SET cost = 489 WHERE id = 'snowy_farm';
UPDATE public.hats SET cost = 578 WHERE id = 'beach_island';
UPDATE public.hats SET cost = 985 WHERE id = 'space_station';
UPDATE public.hats SET cost = 711 WHERE id = 'candyland';
UPDATE public.hats SET cost = 400 WHERE id = 'forest_grove';
UPDATE public.hats SET cost = 511 WHERE id = 'jungle';
UPDATE public.hats SET cost = 667 WHERE id = 'underwater';
UPDATE public.hats SET cost = 467 WHERE id = 'desert_dunes';
UPDATE public.hats SET cost = 556 WHERE id = 'mountain_top';
UPDATE public.hats SET cost = 100 WHERE id = 'party';
UPDATE public.hats SET cost = 114 WHERE id = 'cowboy';
UPDATE public.hats SET cost = 143 WHERE id = 'wizard';
UPDATE public.hats SET cost = 200 WHERE id = 'tophat';
