-- AUTO-GENERATED by tools/regen_studio (Deprecate action) — rebuild-all,
-- edit via the studio, not by hand. Removes items from the game entirely.
-- Safe as bare DELETEs (gas_mask precedent, 20260652): FK cascades clean
-- user_hats / equipped slots / item_drives / achievement rewards.
--
-- Push-day client cleanup checklist (art can lag the DB harmlessly):
--   [ ] acorn_bow: drop from HAT_IMAGES / members catalog + delete assets/images/hats/acorn_bow.png
--   [ ] silver_plume_helm: drop from HAT_IMAGES / members catalog + delete assets/images/hats/silver_plume_helm.png
--   [ ] skull_mask: drop from HAT_IMAGES / members catalog + delete assets/images/hats/skull_mask.png
--   [ ] striped_scarf: drop from HAT_IMAGES / members catalog + delete assets/images/hats/striped_scarf.png
--   [ ] venice_mask: drop from HAT_IMAGES / members catalog + delete assets/images/hats/venice_mask.png
--   [ ] winter_scarf: drop from HAT_IMAGES / members catalog + delete assets/images/hats/winter_scarf.png

DELETE FROM public.hats WHERE id = 'acorn_bow';
DELETE FROM public.hats WHERE id = 'silver_plume_helm';
DELETE FROM public.hats WHERE id = 'skull_mask';
DELETE FROM public.hats WHERE id = 'striped_scarf';
DELETE FROM public.hats WHERE id = 'venice_mask';
DELETE FROM public.hats WHERE id = 'winter_scarf';
