-- Referrals — code-based revival of the deferred Season-1 feature.
-- Per docs/referrals.md. Coexists with the older Sounder system
-- (20260520020000_sounder.sql + 20260530000000_referral_cap.sql) —
-- the new flow uses the same profiles.referred_by column but its
-- own engagement gate, milestone bookkeeping, and code field.
--
-- Adds:
--   profiles.referral_code         — persistent share code (ROSIE-K3T9)
--   profiles.referral_redeemed_at  — when the invitee entered a code
--   profiles.referral_completed_at — when the engagement gate fired
--   profiles.referrals_completed   — cached count for milestone checks
--   profiles.distinct_active_days  — distinct UTC dates the user
--                                    tickled; bumped at most once/day
--   profiles.last_active_date      — drives the distinct-day bump
--
-- RPCs:
--   generate_referral_code(uid)    — server-side, idempotent
--   redeem_referral_code(p_code)   — onboarding code-entry call
--   my_referral_summary()          — Account card hydration
--
-- Engagement gate appended inside update_profile_and_item_count
-- (the live tickle-increment RPC, last rewritten in
-- 20260529000000_ritual_effects_regen.sql). Fires the inviter
-- credit + push exactly once per invitee.
--
-- Backfill: every existing profile gets a code generated lazily on
-- first my_referral_summary() call; this migration also runs a one-
-- shot UPDATE so a long-time user opening the new build already has
-- a code without an extra round-trip.

set check_function_bodies = off;

-- ── 1. New columns on profiles ────────────────────────────────────
-- referred_by already exists (added by 20260520020000_sounder.sql);
-- skipped here. The IF NOT EXISTS guards keep this migration re-
-- runnable in dev.
ALTER TABLE public.profiles
	ADD COLUMN IF NOT EXISTS referral_code         text UNIQUE,
	ADD COLUMN IF NOT EXISTS referral_redeemed_at  timestamptz,
	ADD COLUMN IF NOT EXISTS referral_completed_at timestamptz,
	ADD COLUMN IF NOT EXISTS referrals_completed   int  NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS distinct_active_days  int  NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS last_active_date      date;

CREATE INDEX IF NOT EXISTS idx_profiles_referral_code
	ON public.profiles(referral_code) WHERE referral_code IS NOT NULL;

-- idx_profiles_referred_by already exists from 20260520020000_sounder.sql
-- (profiles_referred_by_idx, same shape) — skipped to avoid duplicate.

-- ── 2. Seed the milestone hat ─────────────────────────────────────
-- Granted to the inviter on their 3rd completed referral (engagement
-- gate crossed by the 3rd distinct invitee). The hat must exist in
-- the catalog so user_hats's FK to hats(id) accepts the insert.
INSERT INTO public.hats (id, name, emoji, cost, display_order) VALUES
	('messenger', 'Messenger Hat', '✉️', 0, 950)
ON CONFLICT (id) DO NOTHING;

-- ── 3. generate_referral_code(uid) ───────────────────────────────
-- Idempotent: returns the existing code if the user already has one;
-- otherwise generates from the username prefix + a 4-char random
-- suffix, retrying up to 5 times on collision.
--
-- Prefix rules:
--   - Take the first 5 chars of the username (or 'PIG' if username
--     is NULL — signup happens before UsernameSetup, so the trigger
--     path passes NULL).
--   - Uppercase. Strip non-alphanumerics. Pad with 'X' to 5 chars.
--
-- Codes generated against a NULL username carry the PIGXX prefix
-- and get regenerated by my_referral_summary the first time the
-- caller has a username AND their code still starts with PIGXX.
-- That keeps the share-able code legible without a sync trigger.
CREATE OR REPLACE FUNCTION public.generate_referral_code(uid uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
	existing text;
	uname    text;
	prefix   text;
	suffix   text;
	candidate text;
	attempts int := 0;
BEGIN
	-- Idempotency check.
	SELECT referral_code, username INTO existing, uname
		FROM public.profiles WHERE id = uid;
	IF existing IS NOT NULL THEN
		RETURN existing;
	END IF;

	-- Build the prefix. Strip non-alphanumeric, uppercase, pad with X.
	prefix := COALESCE(
		regexp_replace(upper(COALESCE(uname, 'PIG')), '[^A-Z0-9]', '', 'g'),
		'PIG'
	);
	IF prefix = '' THEN prefix := 'PIG'; END IF;
	prefix := substr(prefix, 1, 5);
	prefix := rpad(prefix, 5, 'X');

	-- Try up to 5 times to find a non-colliding suffix.
	WHILE attempts < 5 LOOP
		suffix := '';
		FOR _i IN 1..4 LOOP
			-- A-Z and 0-9 = 36 chars; chr(48..57) = '0'..'9', chr(65..90) = 'A'..'Z'.
			DECLARE
				r int := floor(random() * 36)::int;
			BEGIN
				IF r < 10 THEN
					suffix := suffix || chr(48 + r);
				ELSE
					suffix := suffix || chr(65 + (r - 10));
				END IF;
			END;
		END LOOP;
		candidate := prefix || '-' || suffix;

		IF NOT EXISTS (
			SELECT 1 FROM public.profiles WHERE referral_code = candidate
		) THEN
			UPDATE public.profiles SET referral_code = candidate WHERE id = uid;
			RETURN candidate;
		END IF;
		attempts := attempts + 1;
	END LOOP;

	-- 5 collisions in a row is astronomically unlikely (36^4 ≈ 1.6M
	-- per prefix); if we somehow get here, fall back to a timestamp-
	-- derived suffix so the call never returns NULL.
	candidate := prefix || '-' || substr(md5(uid::text || clock_timestamp()::text), 1, 4);
	UPDATE public.profiles SET referral_code = upper(candidate) WHERE id = uid;
	RETURN upper(candidate);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.generate_referral_code(uuid) TO authenticated;

-- ── 4. Extend handle_new_user to seed a referral code ────────────
-- Body is the LIVE definition from 20260550000000_restore_new_user_tickles.sql
-- with the generate_referral_code() call appended. Username is NULL
-- at signup time; the resulting PIGXX-prefixed code is upgraded
-- lazily by my_referral_summary once the user picks a username.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
	INSERT INTO public.profiles (id, full_name, avatar_url)
	VALUES (
		new.id,
		new.raw_user_meta_data->>'full_name',
		new.raw_user_meta_data->>'avatar_url'
	);

	INSERT INTO public.user_hats (user_id, hat_id)
	VALUES (new.id, 'homestead_barn')
	ON CONFLICT (user_id, hat_id) DO NOTHING;

	INSERT INTO public.user_items (user_id, item_count, last_increment)
	VALUES (new.id, 10, now())
	ON CONFLICT (user_id) DO NOTHING;

	-- Seed the referral code so the Account card always has something
	-- to render. NULL username → PIGXX prefix, upgraded lazily later.
	PERFORM public.generate_referral_code(new.id);

	RETURN new;
END;
$function$;

-- ── 5. redeem_referral_code(p_code) ──────────────────────────────
-- All five server-side checks (per spec). On failure returns a
-- typed reason rather than throwing, so the onboarding step can
-- map to user-facing copy without try/catch.
CREATE OR REPLACE FUNCTION public.redeem_referral_code(p_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
	caller_id        uuid := auth.uid();
	caller_referred  uuid;
	caller_created   timestamptz;
	caller_tickles   bigint;
	inviter_id       uuid;
	inviter_name     text;
	normalized       text;
BEGIN
	IF caller_id IS NULL THEN
		RETURN jsonb_build_object('ok', false, 'reason', 'unauthenticated');
	END IF;

	normalized := upper(trim(COALESCE(p_code, '')));
	IF normalized = '' THEN
		RETURN jsonb_build_object('ok', false, 'reason', 'code_not_found');
	END IF;

	-- 1. Caller hasn't already redeemed a code.
	SELECT referred_by INTO caller_referred
		FROM public.profiles WHERE id = caller_id;
	IF caller_referred IS NOT NULL THEN
		RETURN jsonb_build_object('ok', false, 'reason', 'already_redeemed');
	END IF;

	-- 2. The code maps to an actual profile.
	SELECT id, username INTO inviter_id, inviter_name
		FROM public.profiles WHERE referral_code = normalized;
	IF inviter_id IS NULL THEN
		RETURN jsonb_build_object('ok', false, 'reason', 'code_not_found');
	END IF;

	-- 3. Self-referral guard.
	IF inviter_id = caller_id THEN
		RETURN jsonb_build_object('ok', false, 'reason', 'self_referral');
	END IF;

	-- 4. Account is < 24h old.
	SELECT created_at INTO caller_created FROM auth.users WHERE id = caller_id;
	IF caller_created IS NULL OR caller_created < now() - interval '24 hours' THEN
		RETURN jsonb_build_object('ok', false, 'reason', 'too_old');
	END IF;

	-- 5. Caller has tickled fewer than 5 times.
	SELECT tickles_earned INTO caller_tickles
		FROM public.profiles WHERE id = caller_id;
	IF COALESCE(caller_tickles, 0) >= 5 THEN
		RETURN jsonb_build_object('ok', false, 'reason', 'too_active');
	END IF;

	-- All checks passed: attribute + pay the invitee bonus.
	UPDATE public.profiles
		SET referred_by          = inviter_id,
		    referral_redeemed_at = now(),
		    counter              = counter + 50
		WHERE id = caller_id;

	RETURN jsonb_build_object(
		'ok', true,
		'inviter_username', inviter_name
	);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.redeem_referral_code(text) TO authenticated;

-- ── 6. my_referral_summary() ─────────────────────────────────────
-- Account card hydration. Lazily upgrades a PIGXX-prefixed code to
-- a username-prefixed one if the user has since picked a name.
CREATE OR REPLACE FUNCTION public.my_referral_summary()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
	caller_id      uuid := auth.uid();
	code           text;
	uname          text;
	completed      int;
	pending        int;
	next_milestone int;
BEGIN
	IF caller_id IS NULL THEN
		RETURN jsonb_build_object('ok', false, 'reason', 'unauthenticated');
	END IF;

	SELECT referral_code, username, referrals_completed
		INTO code, uname, completed
		FROM public.profiles WHERE id = caller_id;

	-- Lazy generation: backfill never seen, or PIGXX prefix from
	-- pre-username signup that now has a username.
	IF code IS NULL OR (code LIKE 'PIGXX-%' AND uname IS NOT NULL) THEN
		-- For the PIGXX upgrade we have to clear the old code first
		-- so generate_referral_code's idempotency check falls through.
		IF code IS NOT NULL THEN
			UPDATE public.profiles SET referral_code = NULL WHERE id = caller_id;
		END IF;
		code := public.generate_referral_code(caller_id);
	END IF;

	-- Pending = redeemed-but-not-completed referrals pointing at me.
	SELECT COUNT(*)::int INTO pending
		FROM public.profiles
		WHERE referred_by = caller_id
		  AND referral_completed_at IS NULL;

	-- Single milestone in v1 is at 3 (Messenger Hat); null past it.
	next_milestone := CASE
		WHEN COALESCE(completed, 0) < 3 THEN 3
		ELSE NULL
	END;

	RETURN jsonb_build_object(
		'ok',                  true,
		'code',                code,
		'referrals_completed', COALESCE(completed, 0),
		'referrals_pending',   COALESCE(pending,   0),
		'next_milestone_at',   next_milestone
	);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.my_referral_summary() TO authenticated;

-- ── 7. Engagement gate — appended to update_profile_and_item_count
-- Body is the LIVE definition from
-- 20260529000000_ritual_effects_regen.sql, with the active-day bump
-- + referral completion block appended after the tickle-increment.
-- All earlier logic (regen, cap, lucky, battle-pass) is byte-identical.
--
-- Why inline vs trigger: the spec calls for atomic completion; the
-- caller's tickles_earned has already been bumped via UPDATE...SET
-- counter = ... by the time we read it, so we re-read inside the
-- same transaction. A separate AFTER UPDATE trigger would also work
-- but it's a heavier surface for one feature.
CREATE OR REPLACE FUNCTION public.update_profile_and_item_count(uid uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
	is_vip boolean;
	cap_val int;
	regen_secs int;
	intervals_elapsed int;
	current_balance int;
	new_balance int;
	active_season_id text;
	bumped_counter bigint;
	lucky_numbers integer[];
	lucky_won int := NULL;
	-- Engagement-gate locals.
	caller_referred       uuid;
	caller_completed_at   timestamptz;
	caller_tickles_total  bigint;
	caller_active_days    int;
	caller_last_date      date;
	inviter_name          text;
	invitee_name          text;
	new_completion_count  int;
BEGIN
	SELECT COALESCE(profiles.is_vip, false) INTO is_vip
	FROM public.profiles WHERE id = uid;

	cap_val := CASE WHEN is_vip THEN 50 ELSE 25 END;
	regen_secs := public.regen_secs_for(uid);

	SELECT
		GREATEST(0, floor(EXTRACT(EPOCH FROM (now() - last_increment)) / regen_secs)::int),
		item_count
	INTO intervals_elapsed, current_balance
	FROM public.user_items
	WHERE user_id = uid
	FOR UPDATE;

	IF current_balance IS NULL THEN
		RAISE EXCEPTION 'No user_items row for user %', uid;
	END IF;

	current_balance := LEAST(cap_val, current_balance + intervals_elapsed);

	IF current_balance <= 0 THEN
		UPDATE public.user_items
		SET item_count = current_balance,
		    last_increment = last_increment + (intervals_elapsed * (regen_secs * INTERVAL '1 second'))
		WHERE user_id = uid;
		RETURN jsonb_build_object('balance', current_balance, 'lucky_won', null);
	END IF;

	new_balance := current_balance - 1;

	UPDATE public.user_items
	SET item_count = new_balance,
	    last_increment = last_increment + (intervals_elapsed * (regen_secs * INTERVAL '1 second'))
	WHERE user_id = uid;

	-- Personal: balance counter + lifetime tickles
	UPDATE public.profiles
	SET counter = counter + 1,
	    tickles_earned = tickles_earned + 1
	WHERE id = uid;

	-- Battle pass XP
	SELECT id INTO active_season_id
	FROM public.seasons
	WHERE starts_at <= now() AND ends_at >= now()
	ORDER BY starts_at DESC LIMIT 1;

	IF active_season_id IS NOT NULL THEN
		INSERT INTO public.user_season_progress (user_id, season_id, xp)
		VALUES (uid, active_season_id, 1)
		ON CONFLICT (user_id, season_id) DO UPDATE
			SET xp = public.user_season_progress.xp + 1;
	END IF;

	-- Global daily lucky counter — atomic insert-or-bump.
	INSERT INTO public.daily_lucky_state (d, global_counter, numbers)
	     VALUES (CURRENT_DATE, 1, public.roll_lucky_numbers())
	ON CONFLICT (d) DO UPDATE
	     SET global_counter = daily_lucky_state.global_counter + 1
	  RETURNING global_counter, numbers
	     INTO bumped_counter, lucky_numbers;

	-- Did this tickle land on a lucky number?
	IF bumped_counter = ANY(lucky_numbers) THEN
		INSERT INTO public.daily_lucky_claims (d, number, user_id)
		VALUES (CURRENT_DATE, bumped_counter::int, uid)
		ON CONFLICT (d, number) DO NOTHING;

		IF EXISTS (
			SELECT 1 FROM public.daily_lucky_claims
				WHERE d = CURRENT_DATE
				  AND number = bumped_counter::int
				  AND user_id = uid
		) THEN
			lucky_won := bumped_counter::int;
			UPDATE public.profiles
			SET counter = counter + 5,
			    tickles_earned = tickles_earned + 5
			WHERE id = uid;
		END IF;
	END IF;

	-- ── Referral engagement gate ────────────────────────────────
	-- Bump distinct_active_days at most once per UTC calendar day,
	-- then fire the inviter credit ONCE when the invitee crosses
	-- BOTH the tickle threshold AND the active-day threshold.
	SELECT referred_by, referral_completed_at, tickles_earned,
	       distinct_active_days, last_active_date, username
		INTO caller_referred, caller_completed_at, caller_tickles_total,
		     caller_active_days, caller_last_date, invitee_name
		FROM public.profiles WHERE id = uid;

	IF caller_last_date IS DISTINCT FROM CURRENT_DATE THEN
		UPDATE public.profiles
			SET distinct_active_days = COALESCE(distinct_active_days, 0) + 1,
			    last_active_date     = CURRENT_DATE
			WHERE id = uid;
		caller_active_days := COALESCE(caller_active_days, 0) + 1;
	END IF;

	IF caller_referred IS NOT NULL
	   AND caller_completed_at IS NULL
	   AND caller_tickles_total >= 100
	   AND caller_active_days >= 3
	THEN
		UPDATE public.profiles
			SET referral_completed_at = now()
			WHERE id = uid;

		UPDATE public.profiles
			SET counter             = counter + 100,
			    referrals_completed = referrals_completed + 1
			WHERE id = caller_referred
			RETURNING referrals_completed, username
				INTO new_completion_count, inviter_name;

		-- Milestone: grant the Messenger Hat on the inviter's 3rd
		-- completed referral. Idempotent via user_hats's PK.
		IF new_completion_count = 3 THEN
			INSERT INTO public.user_hats (user_id, hat_id)
				VALUES (caller_referred, 'messenger')
				ON CONFLICT (user_id, hat_id) DO NOTHING;
		END IF;

		-- Push notify the inviter. Fire-and-forget — a push failure
		-- must never roll back the engagement-gate write.
		BEGIN
			PERFORM public.send_push_to_user(
				caller_referred,
				'Your friend ' || COALESCE(invitee_name, 'a pig') || ' made it!',
				CASE
					WHEN new_completion_count = 3
						THEN '+100 snouts AND the Messenger Hat. Tap to see.'
					ELSE '+100 snouts. Tap to see your sounder.'
				END,
				jsonb_build_object(
					'kind',   'referral_completed',
					'screen', 'account'
				)
			);
		EXCEPTION WHEN OTHERS THEN
			NULL;
		END;
	END IF;
	-- ── end engagement gate ─────────────────────────────────────

	RETURN jsonb_build_object(
		'balance', new_balance,
		'lucky_won', lucky_won,
		'global_counter', bumped_counter
	);
END;
$function$;

-- ── 8. Backfill referral_code for existing users ────────────────
-- Idempotent: generate_referral_code is a no-op if a code already
-- exists. Runs at deploy time so a long-time user opening the new
-- build already has a code on the Account card.
DO $$
DECLARE
	r record;
BEGIN
	FOR r IN SELECT id FROM public.profiles WHERE referral_code IS NULL LOOP
		PERFORM public.generate_referral_code(r.id);
	END LOOP;
END
$$;
