-- World Cup 2026 shop content seed: 47 qualified-team flag cosmetics
-- (category 'flag') + a country title each. Iran is excluded (sanctions
-- denylist, see docs/world-cup-countries.md). Generated by
-- scripts/gen_world_cup_seed.py — edit there, not here.
--
-- Flags are a NEW 'flag' category; client placement + HAT_IMAGES wiring lives
-- in constants/worldCupFlags.ts. daily_shop() should be updated to EXCLUDE
-- category='flag' so these only appear in the special World Cup shop.

-- Allow 'world_cup' as a titles source.
ALTER TABLE public.titles DROP CONSTRAINT IF EXISTS titles_source_check;
ALTER TABLE public.titles
  ADD CONSTRAINT titles_source_check
  CHECK (source IS NULL OR source IN
    ('battle_pass', 'shop', 'lucky', 'sounder', 'achievement', 'season', 'world_cup'));

INSERT INTO public.hats
  (id, name, emoji, image_path, cost, display_order, category, rarity, description)
VALUES
  ('flag_brazil', 'Brazil', NULL, 'hats/flags/brazil.png', 300, 5000, 'flag', 'rare', 'Fly the colors of Brazil.'),
  ('flag_argentina', 'Argentina', NULL, 'hats/flags/argentina.png', 300, 5001, 'flag', 'rare', 'Fly the colors of Argentina.'),
  ('flag_france', 'France', NULL, 'hats/flags/france.png', 300, 5002, 'flag', 'rare', 'Fly the colors of France.'),
  ('flag_japan', 'Japan', NULL, 'hats/flags/japan.png', 300, 5003, 'flag', 'rare', 'Fly the colors of Japan.'),
  ('flag_mexico', 'Mexico', NULL, 'hats/flags/mexico.png', 300, 5004, 'flag', 'rare', 'Fly the colors of Mexico.'),
  ('flag_usa', 'United States', NULL, 'hats/flags/usa.png', 300, 5005, 'flag', 'rare', 'Fly the colors of United States.'),
  ('flag_spain', 'Spain', NULL, 'hats/flags/spain.png', 300, 5006, 'flag', 'rare', 'Fly the colors of Spain.'),
  ('flag_england', 'England', NULL, 'hats/flags/england.png', 300, 5007, 'flag', 'rare', 'Fly the colors of England.'),
  ('flag_portugal', 'Portugal', NULL, 'hats/flags/portugal.png', 300, 5008, 'flag', 'rare', 'Fly the colors of Portugal.'),
  ('flag_germany', 'Germany', NULL, 'hats/flags/germany.png', 300, 5009, 'flag', 'rare', 'Fly the colors of Germany.'),
  ('flag_netherlands', 'Netherlands', NULL, 'hats/flags/netherlands.png', 300, 5010, 'flag', 'rare', 'Fly the colors of Netherlands.'),
  ('flag_belgium', 'Belgium', NULL, 'hats/flags/belgium.png', 300, 5011, 'flag', 'rare', 'Fly the colors of Belgium.'),
  ('flag_croatia', 'Croatia', NULL, 'hats/flags/croatia.png', 300, 5012, 'flag', 'rare', 'Fly the colors of Croatia.'),
  ('flag_norway', 'Norway', NULL, 'hats/flags/norway.png', 300, 5013, 'flag', 'rare', 'Fly the colors of Norway.'),
  ('flag_switzerland', 'Switzerland', NULL, 'hats/flags/switzerland.png', 300, 5014, 'flag', 'rare', 'Fly the colors of Switzerland.'),
  ('flag_austria', 'Austria', NULL, 'hats/flags/austria.png', 300, 5015, 'flag', 'rare', 'Fly the colors of Austria.'),
  ('flag_scotland', 'Scotland', NULL, 'hats/flags/scotland.png', 300, 5016, 'flag', 'rare', 'Fly the colors of Scotland.'),
  ('flag_sweden', 'Sweden', NULL, 'hats/flags/sweden.png', 300, 5017, 'flag', 'rare', 'Fly the colors of Sweden.'),
  ('flag_turkiye', 'Türkiye', NULL, 'hats/flags/turkiye.png', 300, 5018, 'flag', 'rare', 'Fly the colors of Türkiye.'),
  ('flag_czechia', 'Czechia', NULL, 'hats/flags/czechia.png', 300, 5019, 'flag', 'rare', 'Fly the colors of Czechia.'),
  ('flag_bosnia-and-herzegovina', 'Bosnia and Herzegovina', NULL, 'hats/flags/bosnia-and-herzegovina.png', 300, 5020, 'flag', 'rare', 'Fly the colors of Bosnia and Herzegovina.'),
  ('flag_colombia', 'Colombia', NULL, 'hats/flags/colombia.png', 300, 5021, 'flag', 'rare', 'Fly the colors of Colombia.'),
  ('flag_ecuador', 'Ecuador', NULL, 'hats/flags/ecuador.png', 300, 5022, 'flag', 'rare', 'Fly the colors of Ecuador.'),
  ('flag_uruguay', 'Uruguay', NULL, 'hats/flags/uruguay.png', 300, 5023, 'flag', 'rare', 'Fly the colors of Uruguay.'),
  ('flag_paraguay', 'Paraguay', NULL, 'hats/flags/paraguay.png', 300, 5024, 'flag', 'rare', 'Fly the colors of Paraguay.'),
  ('flag_canada', 'Canada', NULL, 'hats/flags/canada.png', 300, 5025, 'flag', 'rare', 'Fly the colors of Canada.'),
  ('flag_panama', 'Panama', NULL, 'hats/flags/panama.png', 300, 5026, 'flag', 'rare', 'Fly the colors of Panama.'),
  ('flag_haiti', 'Haiti', NULL, 'hats/flags/haiti.png', 300, 5027, 'flag', 'rare', 'Fly the colors of Haiti.'),
  ('flag_curacao', 'Curaçao', NULL, 'hats/flags/curacao.png', 300, 5028, 'flag', 'rare', 'Fly the colors of Curaçao.'),
  ('flag_morocco', 'Morocco', NULL, 'hats/flags/morocco.png', 300, 5029, 'flag', 'rare', 'Fly the colors of Morocco.'),
  ('flag_senegal', 'Senegal', NULL, 'hats/flags/senegal.png', 300, 5030, 'flag', 'rare', 'Fly the colors of Senegal.'),
  ('flag_egypt', 'Egypt', NULL, 'hats/flags/egypt.png', 300, 5031, 'flag', 'rare', 'Fly the colors of Egypt.'),
  ('flag_tunisia', 'Tunisia', NULL, 'hats/flags/tunisia.png', 300, 5032, 'flag', 'rare', 'Fly the colors of Tunisia.'),
  ('flag_algeria', 'Algeria', NULL, 'hats/flags/algeria.png', 300, 5033, 'flag', 'rare', 'Fly the colors of Algeria.'),
  ('flag_south-africa', 'South Africa', NULL, 'hats/flags/south-africa.png', 300, 5034, 'flag', 'rare', 'Fly the colors of South Africa.'),
  ('flag_cote-divoire', 'Côte d''Ivoire', NULL, 'hats/flags/cote-divoire.png', 300, 5035, 'flag', 'rare', 'Fly the colors of Côte d''Ivoire.'),
  ('flag_ghana', 'Ghana', NULL, 'hats/flags/ghana.png', 300, 5036, 'flag', 'rare', 'Fly the colors of Ghana.'),
  ('flag_cape-verde', 'Cape Verde', NULL, 'hats/flags/cape-verde.png', 300, 5037, 'flag', 'rare', 'Fly the colors of Cape Verde.'),
  ('flag_dr-congo', 'DR Congo', NULL, 'hats/flags/dr-congo.png', 300, 5038, 'flag', 'rare', 'Fly the colors of DR Congo.'),
  ('flag_south-korea', 'South Korea', NULL, 'hats/flags/south-korea.png', 300, 5039, 'flag', 'rare', 'Fly the colors of South Korea.'),
  ('flag_australia', 'Australia', NULL, 'hats/flags/australia.png', 300, 5040, 'flag', 'rare', 'Fly the colors of Australia.'),
  ('flag_uzbekistan', 'Uzbekistan', NULL, 'hats/flags/uzbekistan.png', 300, 5041, 'flag', 'rare', 'Fly the colors of Uzbekistan.'),
  ('flag_jordan', 'Jordan', NULL, 'hats/flags/jordan.png', 300, 5042, 'flag', 'rare', 'Fly the colors of Jordan.'),
  ('flag_qatar', 'Qatar', NULL, 'hats/flags/qatar.png', 300, 5043, 'flag', 'rare', 'Fly the colors of Qatar.'),
  ('flag_saudi-arabia', 'Saudi Arabia', NULL, 'hats/flags/saudi-arabia.png', 300, 5044, 'flag', 'rare', 'Fly the colors of Saudi Arabia.'),
  ('flag_iraq', 'Iraq', NULL, 'hats/flags/iraq.png', 300, 5045, 'flag', 'rare', 'Fly the colors of Iraq.'),
  ('flag_new-zealand', 'New Zealand', NULL, 'hats/flags/new-zealand.png', 300, 5046, 'flag', 'rare', 'Fly the colors of New Zealand.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.titles
  (id, name, placement, description, source, for_sale, display_order)
VALUES
  ('wc_brazil', 'Samba Star', 'pre', 'World Cup 2026 — represent Brazil.', 'world_cup', false, 5000),
  ('wc_argentina', 'Albiceleste Faithful', 'pre', 'World Cup 2026 — represent Argentina.', 'world_cup', false, 5001),
  ('wc_france', 'Les Bleus Beloved', 'pre', 'World Cup 2026 — represent France.', 'world_cup', false, 5002),
  ('wc_japan', 'Samurai-Blue Buddy', 'pre', 'World Cup 2026 — represent Japan.', 'world_cup', false, 5003),
  ('wc_mexico', 'El-Tri Treasure', 'pre', 'World Cup 2026 — represent Mexico.', 'world_cup', false, 5004),
  ('wc_usa', 'Stars-and-Stripes Star', 'pre', 'World Cup 2026 — represent United States.', 'world_cup', false, 5005),
  ('wc_spain', 'La Roja Loyal', 'pre', 'World Cup 2026 — represent Spain.', 'world_cup', false, 5006),
  ('wc_england', 'Three-Lions Loyal', 'pre', 'World Cup 2026 — represent England.', 'world_cup', false, 5007),
  ('wc_portugal', 'Selecção Sweetheart', 'pre', 'World Cup 2026 — represent Portugal.', 'world_cup', false, 5008),
  ('wc_germany', 'Mannschaft Mate', 'pre', 'World Cup 2026 — represent Germany.', 'world_cup', false, 5009),
  ('wc_netherlands', 'Oranje Companion', 'pre', 'World Cup 2026 — represent Netherlands.', 'world_cup', false, 5010),
  ('wc_belgium', 'Red Devil Darling', 'pre', 'World Cup 2026 — represent Belgium.', 'world_cup', false, 5011),
  ('wc_croatia', 'Vatreni Friend', 'pre', 'World Cup 2026 — represent Croatia.', 'world_cup', false, 5012),
  ('wc_norway', 'Fjord-Sider Friend', 'pre', 'World Cup 2026 — represent Norway.', 'world_cup', false, 5013),
  ('wc_switzerland', 'Alpine-Meadow Mate', 'pre', 'World Cup 2026 — represent Switzerland.', 'world_cup', false, 5014),
  ('wc_austria', 'Edelweiss Whistler', 'pre', 'World Cup 2026 — represent Austria.', 'world_cup', false, 5015),
  ('wc_scotland', 'Tartan-Army Buddy', 'pre', 'World Cup 2026 — represent Scotland.', 'world_cup', false, 5016),
  ('wc_sweden', 'Blågult Buddy', 'pre', 'World Cup 2026 — represent Sweden.', 'world_cup', false, 5017),
  ('wc_turkiye', 'Crescent Cuddler', 'pre', 'World Cup 2026 — represent Türkiye.', 'world_cup', false, 5018),
  ('wc_czechia', 'Bohemian Bell', 'pre', 'World Cup 2026 — represent Czechia.', 'world_cup', false, 5019),
  ('wc_bosnia-and-herzegovina', 'Dragon of the Balkans', 'pre', 'World Cup 2026 — represent Bosnia and Herzegovina.', 'world_cup', false, 5020),
  ('wc_colombia', 'Cafetero Companion', 'pre', 'World Cup 2026 — represent Colombia.', 'world_cup', false, 5021),
  ('wc_ecuador', 'Tri-Color Tracker', 'pre', 'World Cup 2026 — represent Ecuador.', 'world_cup', false, 5022),
  ('wc_uruguay', 'Celeste Companion', 'pre', 'World Cup 2026 — represent Uruguay.', 'world_cup', false, 5023),
  ('wc_paraguay', 'Guaraní Guardian', 'pre', 'World Cup 2026 — represent Paraguay.', 'world_cup', false, 5024),
  ('wc_canada', 'Maple-Leaf Mate', 'pre', 'World Cup 2026 — represent Canada.', 'world_cup', false, 5025),
  ('wc_panama', 'Canal-Side Companion', 'pre', 'World Cup 2026 — represent Panama.', 'world_cup', false, 5026),
  ('wc_haiti', 'Bicolore Buddy', 'pre', 'World Cup 2026 — represent Haiti.', 'world_cup', false, 5027),
  ('wc_curacao', 'Dushi-Isle Pal', 'pre', 'World Cup 2026 — represent Curaçao.', 'world_cup', false, 5028),
  ('wc_morocco', 'Atlas-Lion Loyal', 'pre', 'World Cup 2026 — represent Morocco.', 'world_cup', false, 5029),
  ('wc_senegal', 'Lion-of-Teranga Loyal', 'pre', 'World Cup 2026 — represent Senegal.', 'world_cup', false, 5030),
  ('wc_egypt', 'Pharaoh''s Friend', 'pre', 'World Cup 2026 — represent Egypt.', 'world_cup', false, 5031),
  ('wc_tunisia', 'Carthage-Eagle Friend', 'pre', 'World Cup 2026 — represent Tunisia.', 'world_cup', false, 5032),
  ('wc_algeria', 'Desert-Fox Friend', 'pre', 'World Cup 2026 — represent Algeria.', 'world_cup', false, 5033),
  ('wc_south-africa', 'Bafana-Bafana Buddy', 'pre', 'World Cup 2026 — represent South Africa.', 'world_cup', false, 5034),
  ('wc_cote-divoire', 'Elephant Friend', 'pre', 'World Cup 2026 — represent Côte d''Ivoire.', 'world_cup', false, 5035),
  ('wc_ghana', 'Black-Star Beloved', 'pre', 'World Cup 2026 — represent Ghana.', 'world_cup', false, 5036),
  ('wc_cape-verde', 'Blue-Shark Buddy', 'pre', 'World Cup 2026 — represent Cape Verde.', 'world_cup', false, 5037),
  ('wc_dr-congo', 'Leopard-Hearted Friend', 'pre', 'World Cup 2026 — represent DR Congo.', 'world_cup', false, 5038),
  ('wc_south-korea', 'Taeguk-Warrior Buddy', 'pre', 'World Cup 2026 — represent South Korea.', 'world_cup', false, 5039),
  ('wc_australia', 'Socceroo Sweetheart', 'pre', 'World Cup 2026 — represent Australia.', 'world_cup', false, 5040),
  ('wc_uzbekistan', 'Silk-Road Wanderer', 'pre', 'World Cup 2026 — represent Uzbekistan.', 'world_cup', false, 5041),
  ('wc_jordan', 'Chivalrous Friend', 'pre', 'World Cup 2026 — represent Jordan.', 'world_cup', false, 5042),
  ('wc_qatar', 'Maroon-Wave Friend', 'pre', 'World Cup 2026 — represent Qatar.', 'world_cup', false, 5043),
  ('wc_saudi-arabia', 'Green-Falcon Friend', 'pre', 'World Cup 2026 — represent Saudi Arabia.', 'world_cup', false, 5044),
  ('wc_iraq', 'Mesopotamia Friend', 'pre', 'World Cup 2026 — represent Iraq.', 'world_cup', false, 5045),
  ('wc_new-zealand', 'All-White Companion', 'pre', 'World Cup 2026 — represent New Zealand.', 'world_cup', false, 5046)
ON CONFLICT (id) DO NOTHING;
