#!/usr/bin/env node
// Builds tools/anchor-editor/items_data.js — a static JS file the
// editor reads to know each item's base overlay + category. Re-run
// after adding/removing items or re-generating HAT_OVERLAYS.
//
// Pulls from:
//   - constants/hat_overlays.generated.ts (auto-generated overlays)
//   - constants/hats.ts (manual HAT_OVERLAYS overrides + CATEGORY tables)
//   - supabase/migrations/20260502030000_shop_catalog.sql (id → category)

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");

const overlaysSrc = readFileSync(
	resolve(ROOT, "constants/hat_overlays.generated.ts"),
	"utf8",
);
const hatsSrc = readFileSync(resolve(ROOT, "constants/hats.ts"), "utf8");
const catalogSrc = readFileSync(
	resolve(ROOT, "supabase/migrations/20260502030000_shop_catalog.sql"),
	"utf8",
);

// Slice the source between `export const NAME` and the next `};` so we
// only parse entries inside that specific block (avoids confusing
// CATEGORY_OVERLAYS for HAT_OVERLAYS).
function sliceBlock(src, blockName) {
	const startIdx = src.indexOf(`export const ${blockName}`);
	if (startIdx < 0) return "";
	// Find the matching opening brace, then walk to its matching close.
	const openBrace = src.indexOf("{", startIdx);
	if (openBrace < 0) return "";
	let depth = 0;
	for (let i = openBrace; i < src.length; i++) {
		const c = src[i];
		if (c === "{") depth++;
		else if (c === "}") {
			depth--;
			if (depth === 0) return src.slice(openBrace + 1, i);
		}
	}
	return "";
}

// Parse `id: { bottom: N, left: N, width: N, height: N[, anchor: "..."] }`
// entries from a sliced block. Allows extra fields after height so the
// anchor override travels through.
function parseOverlays(src) {
	const re =
		/(\w+)\s*:\s*\{\s*bottom\s*:\s*(-?\d+)\s*,\s*left\s*:\s*(-?\d+)\s*,\s*width\s*:\s*(-?\d+)\s*,\s*height\s*:\s*(-?\d+)(?:\s*,\s*anchor\s*:\s*"([a-z_]+)")?[\s\S]*?\}/g;
	const out = {};
	let m;
	while ((m = re.exec(src))) {
		const entry = {
			bottom: +m[2],
			left: +m[3],
			width: +m[4],
			height: +m[5],
		};
		if (m[6]) entry.anchor = m[6];
		out[m[1]] = entry;
	}
	return out;
}

// Parse `(id, name, emoji, cost, display_order, category, rarity, description),`
// — 6th column is category.
function parseCategories(src) {
	const re = /\('([^']+)'\s*,(?:[^,]+,){4}\s*'([^']+)'\s*,/g;
	const out = {};
	let m;
	while ((m = re.exec(src))) {
		out[m[1]] = m[2];
	}
	// 5 originals predate the catalog migration — they default to 'hat'
	// except monocle which is glasses. Hardcode here so the preview has
	// a category for everyone.
	if (!out["wizard"]) out["wizard"] = "hat";
	if (!out["cowboy"]) out["cowboy"] = "hat";
	if (!out["tophat"]) out["tophat"] = "hat";
	if (!out["party"]) out["party"] = "hat";
	if (!out["monocle"]) out["monocle"] = "glasses";
	return out;
}

const generated = parseOverlays(sliceBlock(overlaysSrc, "HAT_OVERLAYS_GENERATED"));
const manual = parseOverlays(sliceBlock(hatsSrc, "HAT_OVERLAYS"));
const overlays = { ...generated, ...manual };

const categories = parseCategories(catalogSrc);

// Minimal companion tables — small enough to hardcode. Keep in sync
// with constants/hats.ts manually; these change rarely.
const STATIC_HEADER = `// AUTO-GENERATED by tools/anchor-editor/build-data.mjs — DO NOT EDIT.
// Re-run: node tools/anchor-editor/build-data.mjs

// Anchor each category attaches to (from constants/hats.ts CATEGORY_ANCHORS).
const CATEGORY_ANCHORS = {
	hat: "head", bow: "head", glasses: "eyes", mask: "eyes",
	scarf: "neck", necklace: "neck", cape: "body", held: "hand_r",
	aura: "body", background: "body",
};

// Pivot fraction within item bbox that contacts the anchor (from CATEGORY_PIVOTS).
const CATEGORY_PIVOTS = {
	hat: { x: 0.5, y: 1.0 }, bow: { x: 0.5, y: 1.0 },
	glasses: { x: 0.5, y: 0.5 }, mask: { x: 0.5, y: 0.5 },
	scarf: { x: 0.5, y: 0.0 }, necklace: { x: 0.5, y: 0.0 },
	cape: { x: 0.5, y: 0.0 }, held: { x: 0.0, y: 1.0 },
	aura: { x: 0.5, y: 0.5 }, background: { x: 0.5, y: 0.5 },
};

// Default position + size per category (from CATEGORY_OVERLAYS). Items
// without an explicit HAT_OVERLAYS entry inherit from here.
const CATEGORY_OVERLAYS_DATA = {
	hat:        { bottom: 245, left: 88,  width: 125, height: 125 },
	glasses:    { bottom: 179, left: 95,  width: 110, height: 50  },
	bow:        { bottom: 255, left: 120, width: 60,  height: 50  },
	scarf:      { bottom: 70,  left: 70,  width: 160, height: 70  },
	mask:       { bottom: 145, left: 111, width: 130, height: 95  },
	necklace:   { bottom: 30,  left: 115, width: 110, height: 50  },
	cape:       { bottom: 25,  left: 35,  width: 230, height: 195 },
	held:       { bottom: 34,  left: 235, width: 80,  height: 76  },
	aura:       { bottom: 0,   left: 0,   width: 300, height: 300 },
	background: { bottom: 0,   left: 0,   width: 300, height: 300 },
};

// Per-category per-anim shift (from CATEGORY_PERANIM_SHIFTS). Empty
// now that per-frame eye anchors handle the sad-glasses droop.
const CATEGORY_PERANIM_SHIFTS = {};

// Items that render BEHIND the pig (z-order from Z_BEHIND_PIG).
const Z_BEHIND_PIG = {
	background: true, aura: true, cape: true,
};

// Per-item anchor overrides (from HAT_OVERLAYS[id].anchor). Most items
// use the category default; this lists the exceptions.
const ITEM_ANCHOR_OVERRIDE = {
	monocle: "eye_r",
};
`;

const out = [
	STATIC_HEADER,
	`// Per-item base overlay (bottom/left/width/height in 300×300 card space).`,
	`const HAT_OVERLAYS_DATA = ${JSON.stringify(overlays, null, "\t")};`,
	"",
	`// id → category (drives anchor + pivot + z-order lookups).`,
	`const ITEM_CATEGORY = ${JSON.stringify(categories, null, "\t")};`,
	"",
].join("\n");

const outPath = resolve(__dirname, "items_data.js");
writeFileSync(outPath, out);
console.log(
	`wrote ${outPath} (${Object.keys(overlays).length} overlays, ${
		Object.keys(categories).length
	} categories)`,
);
