// AUTO-GENERATED by tools/anchor-editor/build-data.mjs — DO NOT EDIT.
// Re-run: node tools/anchor-editor/build-data.mjs

// Anchor each category attaches to (from constants/hats.ts CATEGORY_ANCHORS).
const CATEGORY_ANCHORS = {
	hat: "head", bow: "head", glasses: "eyes", mask: "eyes",
	scarf: "neck", necklace: "neck", cape: "body", held: "hand_r",
	aura: "body", background: "body",
};

// Pivot fraction within item bbox that contacts the anchor (from CATEGORY_PIVOTS).
const CATEGORY_PIVOTS = {
	hat: { x: 0.5, y: 1.0 }, bow: { x: 0.5, y: 1.0 },
	glasses: { x: 0.5, y: 0.5 }, mask: { x: 0.5, y: 0.5 },
	scarf: { x: 0.5, y: 0.0 }, necklace: { x: 0.5, y: 0.0 },
	cape: { x: 0.5, y: 0.0 }, held: { x: 0.0, y: 1.0 },
	aura: { x: 0.5, y: 0.5 }, background: { x: 0.5, y: 0.5 },
};

// Default position + size per category (from CATEGORY_OVERLAYS). Items
// without an explicit HAT_OVERLAYS entry inherit from here.
const CATEGORY_OVERLAYS_DATA = {
	hat:        { bottom: 245, left: 88,  width: 125, height: 125 },
	glasses:    { bottom: 179, left: 95,  width: 110, height: 50  },
	bow:        { bottom: 255, left: 120, width: 60,  height: 50  },
	scarf:      { bottom: 70,  left: 70,  width: 160, height: 70  },
	mask:       { bottom: 145, left: 111, width: 130, height: 95  },
	necklace:   { bottom: 30,  left: 115, width: 110, height: 50  },
	cape:       { bottom: 25,  left: 35,  width: 230, height: 195 },
	held:       { bottom: 34,  left: 235, width: 80,  height: 76  },
	aura:       { bottom: 0,   left: 0,   width: 300, height: 300 },
	background: { bottom: 0,   left: 0,   width: 300, height: 300 },
};

// Per-category per-anim shift (from CATEGORY_PERANIM_SHIFTS). Empty
// now that per-frame eye anchors handle the sad-glasses droop.
const CATEGORY_PERANIM_SHIFTS = {};

// Items that render BEHIND the pig (z-order from Z_BEHIND_PIG).
const Z_BEHIND_PIG = {
	background: true, aura: true, cape: true,
};

// Per-item anchor overrides (from HAT_OVERLAYS[id].anchor). Most items
// use the category default; this lists the exceptions.
const ITEM_ANCHOR_OVERRIDE = {
	monocle: "eye_r",
};

// Per-item base overlay (bottom/left/width/height in 300×300 card space).
const HAT_OVERLAYS_DATA = {
	"archery_bow": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 58
	},
	"ascot": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"aviator_sunglasses": {
		"bottom": 182,
		"left": 56,
		"width": 216,
		"height": 73
	},
	"balloon": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 148
	},
	"bandana_red": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"beach_island": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"beanie": {
		"bottom": 289,
		"left": 84,
		"width": 160,
		"height": 155
	},
	"bell_collar": {
		"bottom": 119,
		"left": 94,
		"width": 140,
		"height": 85
	},
	"black_bow_tie": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 34
	},
	"bone_necklace": {
		"bottom": 114,
		"left": 94,
		"width": 140,
		"height": 90
	},
	"candyland": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"cape_scarf": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"carnival_mask": {
		"bottom": 159,
		"left": 84,
		"width": 160,
		"height": 120
	},
	"cat_mask": {
		"bottom": 166,
		"left": 84,
		"width": 160,
		"height": 107
	},
	"charm_necklace": {
		"bottom": 114,
		"left": 94,
		"width": 140,
		"height": 90
	},
	"chef_toque": {
		"bottom": 289,
		"left": 84,
		"width": 160,
		"height": 137
	},
	"choker": {
		"bottom": 138,
		"left": 94,
		"width": 140,
		"height": 66
	},
	"coffee_mug": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 81
	},
	"controller": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 48
	},
	"cowboy": {
		"bottom": 224,
		"left": 34,
		"width": 220,
		"height": 157
	},
	"crown": {
		"bottom": 289,
		"left": 84,
		"width": 160,
		"height": 116
	},
	"desert_dunes": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"diamond_pendant": {
		"bottom": 114,
		"left": 94,
		"width": 140,
		"height": 90
	},
	"domino": {
		"bottom": 189,
		"left": 84,
		"width": 160,
		"height": 60
	},
	"electric_aura": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 268
	},
	"emerald_pendant": {
		"bottom": 114,
		"left": 94,
		"width": 140,
		"height": 90
	},
	"ermine_cape": {
		"bottom": 37,
		"left": 44,
		"width": 240,
		"height": 207
	},
	"fire_aura": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 266
	},
	"flowers": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 112
	},
	"forest_grove": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"fur_cape": {
		"bottom": 24,
		"left": 44,
		"width": 240,
		"height": 220
	},
	"gas_mask": {
		"bottom": 159,
		"left": 84,
		"width": 160,
		"height": 120
	},
	"gift_bow": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 53
	},
	"gold_aura": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 284
	},
	"gold_chain": {
		"bottom": 133,
		"left": 94,
		"width": 140,
		"height": 71
	},
	"hair_bow": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 51
	},
	"halo": {
		"bottom": 289,
		"left": 84,
		"width": 160,
		"height": 69
	},
	"heart_sunglasses": {
		"bottom": 183,
		"left": 56,
		"width": 216,
		"height": 72
	},
	"hero_cape": {
		"bottom": 24,
		"left": 44,
		"width": 240,
		"height": 220
	},
	"hero_mask": {
		"bottom": 188,
		"left": 84,
		"width": 160,
		"height": 61
	},
	"holy_aura": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 263
	},
	"ice_aura": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 265
	},
	"ice_cream": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 163
	},
	"jungle": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"knit_scarf": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"leather_cape": {
		"bottom": 24,
		"left": 44,
		"width": 240,
		"height": 220
	},
	"locket": {
		"bottom": 114,
		"left": 94,
		"width": 140,
		"height": 90
	},
	"magic_wand": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 76
	},
	"magician_cape": {
		"bottom": 24,
		"left": 44,
		"width": 240,
		"height": 220
	},
	"magnifier": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 163
	},
	"masquerade": {
		"bottom": 178,
		"left": 84,
		"width": 160,
		"height": 81
	},
	"monocle": {
		"bottom": 146,
		"left": 194,
		"width": 70,
		"height": 70,
		"anchor": "eye_r"
	},
	"mountain_top": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"neckwarmer": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"nerd_glasses": {
		"bottom": 180,
		"left": 56,
		"width": 216,
		"height": 79
	},
	"party": {
		"bottom": 209,
		"left": 89,
		"width": 110,
		"height": 147
	},
	"pearl_necklace": {
		"bottom": 123,
		"left": 94,
		"width": 140,
		"height": 81
	},
	"pencil": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 180
	},
	"petal_aura": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 276
	},
	"pink_bow": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 54
	},
	"pink_glow": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 261
	},
	"pirate_tricorn": {
		"bottom": 289,
		"left": 84,
		"width": 160,
		"height": 83
	},
	"pixel_glasses": {
		"bottom": 191,
		"left": 56,
		"width": 216,
		"height": 56
	},
	"pizza_slice": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 81
	},
	"polka_bow": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 55
	},
	"rainbow_aura": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 270
	},
	"rainbow_bow": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 54
	},
	"rainbow_scarf": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"ribbon_bow": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 64
	},
	"ribbon_choker": {
		"bottom": 120,
		"left": 94,
		"width": 140,
		"height": 84
	},
	"robber_mask": {
		"bottom": 184,
		"left": 84,
		"width": 160,
		"height": 71
	},
	"round_glasses": {
		"bottom": 179,
		"left": 56,
		"width": 216,
		"height": 80
	},
	"royal_cape": {
		"bottom": 24,
		"left": 44,
		"width": 240,
		"height": 220
	},
	"safety_goggles": {
		"bottom": 182,
		"left": 56,
		"width": 216,
		"height": 74
	},
	"shadow_aura": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 248
	},
	"short_cape": {
		"bottom": 101,
		"left": 44,
		"width": 240,
		"height": 143
	},
	"silk_bow": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 59
	},
	"silk_cape": {
		"bottom": 28,
		"left": 44,
		"width": 240,
		"height": 216
	},
	"silk_scarf": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"skull_mask": {
		"bottom": 172,
		"left": 84,
		"width": 160,
		"height": 95
	},
	"sleep_mask": {
		"bottom": 190,
		"left": 84,
		"width": 160,
		"height": 58
	},
	"snowy_farm": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"space_station": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"sparkle_aura": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 256
	},
	"star_cape": {
		"bottom": 24,
		"left": 44,
		"width": 240,
		"height": 220
	},
	"striped_scarf": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"summer_kerchief": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"sunset_farm": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"swim_goggles": {
		"bottom": 184,
		"left": 56,
		"width": 216,
		"height": 69
	},
	"three_d_glasses": {
		"bottom": 189,
		"left": 56,
		"width": 216,
		"height": 60
	},
	"tophat": {
		"bottom": 209,
		"left": 74,
		"width": 140,
		"height": 153
	},
	"toy_sword": {
		"bottom": 34,
		"left": 235,
		"width": 80,
		"height": 180
	},
	"underwater": {
		"bottom": 0,
		"left": 0,
		"width": 300,
		"height": 300
	},
	"vampire_cape": {
		"bottom": 24,
		"left": 44,
		"width": 240,
		"height": 220
	},
	"velvet_bow": {
		"bottom": 273,
		"left": 130,
		"width": 80,
		"height": 53
	},
	"venice_mask": {
		"bottom": 159,
		"left": 84,
		"width": 160,
		"height": 120
	},
	"viking_helmet": {
		"bottom": 289,
		"left": 84,
		"width": 160,
		"height": 103
	},
	"vr_headset": {
		"bottom": 180,
		"left": 56,
		"width": 216,
		"height": 77
	},
	"winter_scarf": {
		"bottom": 134,
		"left": 74,
		"width": 180,
		"height": 80
	},
	"wizard": {
		"bottom": 209,
		"left": 64,
		"width": 160,
		"height": 160
	}
};

// id → category (drives anchor + pivot + z-order lookups).
const ITEM_CATEGORY = {
	"beanie": "hat",
	"crown": "hat",
	"halo": "hat",
	"pirate_tricorn": "hat",
	"chef_toque": "hat",
	"viking_helmet": "hat",
	"round_glasses": "glasses",
	"aviator_sunglasses": "glasses",
	"monocle": "glasses",
	"swim_goggles": "glasses",
	"nerd_glasses": "glasses",
	"three_d_glasses": "glasses",
	"heart_sunglasses": "glasses",
	"pixel_glasses": "glasses",
	"safety_goggles": "glasses",
	"vr_headset": "glasses",
	"pink_bow": "bow",
	"black_bow_tie": "bow",
	"ribbon_bow": "bow",
	"hair_bow": "bow",
	"gift_bow": "bow",
	"archery_bow": "bow",
	"silk_bow": "bow",
	"polka_bow": "bow",
	"velvet_bow": "bow",
	"rainbow_bow": "bow",
	"knit_scarf": "scarf",
	"silk_scarf": "scarf",
	"bandana_red": "scarf",
	"cape_scarf": "scarf",
	"striped_scarf": "scarf",
	"winter_scarf": "scarf",
	"summer_kerchief": "scarf",
	"ascot": "scarf",
	"neckwarmer": "scarf",
	"rainbow_scarf": "scarf",
	"pink_glow": "aura",
	"gold_aura": "aura",
	"rainbow_aura": "aura",
	"fire_aura": "aura",
	"ice_aura": "aura",
	"electric_aura": "aura",
	"shadow_aura": "aura",
	"holy_aura": "aura",
	"sparkle_aura": "aura",
	"petal_aura": "aura",
	"masquerade": "mask",
	"domino": "mask",
	"robber_mask": "mask",
	"sleep_mask": "mask",
	"gas_mask": "mask",
	"carnival_mask": "mask",
	"venice_mask": "mask",
	"cat_mask": "mask",
	"skull_mask": "mask",
	"hero_mask": "mask",
	"royal_cape": "cape",
	"vampire_cape": "cape",
	"hero_cape": "cape",
	"magician_cape": "cape",
	"fur_cape": "cape",
	"silk_cape": "cape",
	"leather_cape": "cape",
	"short_cape": "cape",
	"ermine_cape": "cape",
	"star_cape": "cape",
	"pearl_necklace": "necklace",
	"gold_chain": "necklace",
	"locket": "necklace",
	"bone_necklace": "necklace",
	"charm_necklace": "necklace",
	"diamond_pendant": "necklace",
	"emerald_pendant": "necklace",
	"choker": "necklace",
	"bell_collar": "necklace",
	"ribbon_choker": "necklace",
	"magic_wand": "held",
	"toy_sword": "held",
	"pencil": "held",
	"magnifier": "held",
	"balloon": "held",
	"flowers": "held",
	"ice_cream": "held",
	"pizza_slice": "held",
	"coffee_mug": "held",
	"controller": "held",
	"sunset_farm": "background",
	"snowy_farm": "background",
	"beach_island": "background",
	"space_station": "background",
	"candyland": "background",
	"forest_grove": "background",
	"jungle": "background",
	"underwater": "background",
	"desert_dunes": "background",
	"mountain_top": "background",
	"wizard": "hat",
	"cowboy": "hat",
	"tophat": "hat",
	"party": "hat"
};
